/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/scheduler/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/task-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTaskTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/modules/{module}/unregister": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Platform administrators mark every type of a removed module unavailable. */
        post: operations["retireModule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/cron/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["previewCron"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTasks"];
        put?: never;
        post: operations["createTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTask"];
        put: operations["updateTask"];
        post?: never;
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/tasks/{id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/tasks/{id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/tasks/{id}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restartTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/tasks/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Run now (any task) or run again (a completed one-shot task). Does not change the schedule. */
        post: operations["runTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/tasks/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/tasks/bulk/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Start, stop or restart every periodic task in the caller's scope. */
        post: operations["bulkControl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExecutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/executions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExecution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Long-lived SSE stream of scheduler.execution / scheduler.task events of the caller's tenant (ids and status only). The module closes it at 290 s and the client resumes with last_id. */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/backup/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Export of the caller's tenant (tasks, executions, referenced task types). all=true exports every tenant and is platform-admin only. */
        post: operations["exportBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scheduler/v1/backup/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Loads a backup into the caller's tenant (existing ids are skipped). Task types are restored only for platform administrators, only when absent and always as unavailable. */
        post: operations["importBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description unauthenticated | forbidden | not_found | malformed_body | body_too_large | validation_failed | conflict | temporarily_unavailable | not_implemented | invalid_payload | payload_too_large | payload_too_deep | invalid_cron | cron_too_frequent | invalid_timezone | invalid_options | invalid_run_at | type_unavailable | name_taken | not_periodic | run_in_progress | not_cancellable | invalid_backup */
            reason: string;
            detail?: Record<string, never>;
        };
        /** @enum {string} */
        Kind: "periodic" | "delayed" | "wait_result";
        /** @enum {string} */
        TaskStatus: "active" | "completed" | "cancelled";
        /** @enum {string} */
        TaskState: "enabled" | "stopped" | "completed" | "cancelled";
        /** @enum {string} */
        Validity: "ok" | "type_unavailable" | "payload_invalid";
        /** @enum {string} */
        Scope: "tenant" | "platform";
        /** @enum {string} */
        ExecutionStatus: "queued" | "running" | "succeeded" | "failed" | "skipped" | "timed_out" | "cancelled";
        /** @enum {string} */
        Trigger: "schedule" | "manual" | "catch_up";
        TaskType: {
            name: string;
            module: string;
            display_name: string;
            description?: string;
            /** @description JSON Schema of the payload object (null = any object) */
            payload_schema?: Record<string, never> | null;
            default_cron?: string;
            default_max_retries?: number;
            scope: components["schemas"]["Scope"];
            available: boolean;
            /** Format: date-time */
            registered_at?: string;
            /** Format: date-time */
            unregistered_at?: string | null;
        };
        TaskTypeList: {
            items: components["schemas"]["TaskType"][];
        };
        Task: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            name: string;
            type_name: string;
            type_display_name?: string;
            module: string;
            scope?: components["schemas"]["Scope"];
            kind: components["schemas"]["Kind"];
            payload: Record<string, never>;
            cron?: string;
            timezone?: string;
            /** Format: date-time */
            run_at?: string | null;
            enabled: boolean;
            status: components["schemas"]["TaskStatus"];
            state: components["schemas"]["TaskState"];
            validity: components["schemas"]["Validity"];
            validity_message?: string;
            max_retries?: number;
            timeout_seconds?: number;
            catch_up?: boolean;
            remark?: string;
            /** Format: date-time */
            next_run_at?: string | null;
            /** Format: date-time */
            last_run_at?: string | null;
            last_status?: string;
            last_message?: string;
            run_count?: number;
            missed_count?: number;
            created_by?: string;
            updated_by?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            /**
             * Format: uuid
             * @description wait_result create only: the first attempt to follow
             */
            execution_id?: string;
        };
        TaskPage: {
            items: components["schemas"]["Task"][];
            total: number;
            /** @description the page returned (a page beyond the end answers the last page) */
            page: number;
            page_size: number;
            /** @enum {string} */
            sort: "name" | "type" | "state" | "next_run_at" | "updated_at";
            /** @enum {string} */
            order: "asc" | "desc";
        };
        TaskCreate: {
            name: string;
            type_name: string;
            kind: components["schemas"]["Kind"];
            payload?: Record<string, never>;
            cron?: string;
            timezone?: string;
            /** Format: date-time */
            run_at?: string | null;
            delay_seconds?: number;
            enabled?: boolean;
            remark?: string;
            max_retries?: number;
            timeout_seconds?: number;
            catch_up?: boolean;
        };
        TaskUpdate: {
            name: string;
            payload?: Record<string, never>;
            cron?: string;
            timezone?: string;
            /** Format: date-time */
            run_at?: string | null;
            enabled?: boolean;
            remark?: string;
            max_retries?: number;
            timeout_seconds?: number;
            catch_up?: boolean;
        };
        Execution: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id?: string;
            /** Format: uuid */
            task_id: string;
            task_name?: string;
            /** Format: uuid */
            occurrence_id: string;
            type_name: string;
            module: string;
            trigger: components["schemas"]["Trigger"];
            triggered_by?: string;
            /** Format: date-time */
            scheduled_at?: string;
            /** Format: date-time */
            due_at?: string;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            duration_ms?: number;
            attempt: number;
            max_attempts: number;
            status: components["schemas"]["ExecutionStatus"];
            message?: string;
            /** @description module result: JSON value, or a string when not JSON (single execution only) */
            result?: unknown;
            result_truncated?: boolean;
            /**
             * Format: date-time
             * @description when the attempt was recorded (the history sort field)
             */
            created_at?: string;
        };
        ExecutionPage: {
            items: components["schemas"]["Execution"][];
            total: number;
            /** @description the page returned (a page beyond the end answers the last page) */
            page: number;
            page_size: number;
            /** @enum {string} */
            sort: "created_at" | "status" | "duration" | "trigger";
            /** @enum {string} */
            order: "asc" | "desc";
            counts: {
                succeeded?: number;
                failed?: number;
                other?: number;
            };
        };
        RunAccepted: {
            /** Format: uuid */
            execution_id: string;
        };
        BulkResult: {
            affected: number;
        };
        CronPreview: {
            next: string[];
        };
        Overview: {
            tasks?: {
                enabled?: number;
                stopped?: number;
                completed?: number;
                cancelled?: number;
                type_unavailable?: number;
                payload_invalid?: number;
            };
            runs_24h?: number;
            failures_24h?: number;
            next_due?: {
                task_id?: string;
                name?: string;
                /** Format: date-time */
                next_run_at?: string;
            }[];
            failing?: {
                task_id?: string;
                name?: string;
                last_status?: string;
                last_message?: string;
                /** Format: date-time */
                last_run_at?: string | null;
            }[];
        };
    };
    responses: {
        /** @description refusal */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        csrf: string;
        /** @example 018f3a2b-0000-7000-8000-000000000001 */
        id: string;
        page: number;
        pageSize: number;
        /** @description sort direction; defaults to the chosen field's default direction */
        order: "asc" | "desc";
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description component status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    listTaskTypes: {
        parameters: {
            query?: {
                module?: string;
                available?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description task types visible to the caller */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskTypeList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    retireModule: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                module: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description types retired */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    previewCron: {
        parameters: {
            query: {
                expression: string;
                timezone?: string;
                count?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description next run times */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CronPreview"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listTasks: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                /** @description default name (asc) */
                sort?: "name" | "type" | "state" | "next_run_at" | "updated_at";
                /** @description sort direction; defaults to the chosen field's default direction */
                order?: components["parameters"]["order"];
                kind?: components["schemas"]["Kind"];
                state?: components["schemas"]["TaskState"];
                validity?: components["schemas"]["Validity"];
                type?: string;
                q?: string;
                /** @description platform administrators only */
                tenant_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of tasks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createTask: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description task */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateTask: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            default: components["responses"]["Error"];
        };
    };
    startTask: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    stopTask: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    restartTask: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description restarted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    runTask: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    cancelTask: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    bulkControl: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path: {
                action: "start" | "stop" | "restart";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description tasks affected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listExecutions: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
                /** @description default created_at (desc) */
                sort?: "created_at" | "status" | "duration" | "trigger";
                /** @description sort direction; defaults to the chosen field's default direction */
                order?: components["parameters"]["order"];
                task_id?: string;
                status?: components["schemas"]["ExecutionStatus"][];
                failed_only?: boolean;
                trigger?: components["schemas"]["Trigger"];
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description page of attempts (newest first by default) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example 018f3a2b-0000-7000-8000-000000000001 */
                id: components["parameters"]["id"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description one attempt with its result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Execution"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description figures for the caller's scope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overview"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamEvents: {
        parameters: {
            query?: {
                last_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    exportBackup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    all?: boolean;
                };
            };
        };
        responses: {
            /** @description backup document */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    importBackup: {
        parameters: {
            query?: never;
            header: {
                "X-CSRF-Token": components["parameters"]["csrf"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description import summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
