// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scheduler/v1/scheduler.proto

// Service-to-service contract of the scheduler module (feature 026). Reached
// only over the Freya SPIFFE mTLS channel; nothing here is proxied by the
// gateway.
//
//   - Registration is served by the scheduler and called by the modules that
//     execute tasks. The owning module is the caller's verified SPIFFE
//     identity (spiffe://<td>/svc/<module>), never a request field; every type
//     name must start with "<module>:". The scheduler's policy.yaml lists the
//     modules allowed to call it.
//   - TaskExecutor is served by every module that executes tasks and called by
//     the scheduler only: each module's policy.yaml allows
//     spiffe://<td>/svc/scheduler (and nobody else) to call ExecuteTask, and
//     the module re-checks the peer (sdk pkg/taskexec).
//
// The messages keep the fields of the v3 go-tangra-common contract
// (common.service.v1) where their meaning is unchanged; v4 tenants are UUIDs.

package schedulerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scope of a task type.
type TaskScope int32

const (
	TaskScope_TASK_SCOPE_UNSPECIFIED TaskScope = 0 // treated as TENANT
	TaskScope_TASK_SCOPE_TENANT      TaskScope = 1 // tasks belong to a tenant and run for it
	TaskScope_TASK_SCOPE_PLATFORM    TaskScope = 2 // platform administrators only; runs without a tenant
)

// Enum value maps for TaskScope.
var (
	TaskScope_name = map[int32]string{
		0: "TASK_SCOPE_UNSPECIFIED",
		1: "TASK_SCOPE_TENANT",
		2: "TASK_SCOPE_PLATFORM",
	}
	TaskScope_value = map[string]int32{
		"TASK_SCOPE_UNSPECIFIED": 0,
		"TASK_SCOPE_TENANT":      1,
		"TASK_SCOPE_PLATFORM":    2,
	}
)

func (x TaskScope) Enum() *TaskScope {
	p := new(TaskScope)
	*p = x
	return p
}

func (x TaskScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskScope) Descriptor() protoreflect.EnumDescriptor {
	return file_scheduler_v1_scheduler_proto_enumTypes[0].Descriptor()
}

func (TaskScope) Type() protoreflect.EnumType {
	return &file_scheduler_v1_scheduler_proto_enumTypes[0]
}

func (x TaskScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskScope.Descriptor instead.
func (TaskScope) EnumDescriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

// TaskTypeDescriptor describes one executable task type.
type TaskTypeDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Globally unique name "<module>:<action>", action ^[a-z][a-z0-9-]{0,62}$.
	TaskType        string    `protobuf:"bytes,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	DisplayName     string    `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`                // 1..200
	Description     string    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`                                   // <= 2000
	PayloadSchema   string    `protobuf:"bytes,4,opt,name=payload_schema,json=payloadSchema,proto3" json:"payload_schema,omitempty"`          // JSON Schema (object), <= 64 KiB; empty = any JSON object
	DefaultCron     string    `protobuf:"bytes,5,opt,name=default_cron,json=defaultCron,proto3" json:"default_cron,omitempty"`                // 5-field cron or empty (no suggested schedule)
	DefaultMaxRetry int32     `protobuf:"varint,6,opt,name=default_max_retry,json=defaultMaxRetry,proto3" json:"default_max_retry,omitempty"` // 0..10
	Scope           TaskScope `protobuf:"varint,7,opt,name=scope,proto3,enum=scheduler.v1.TaskScope" json:"scope,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TaskTypeDescriptor) Reset() {
	*x = TaskTypeDescriptor{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskTypeDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskTypeDescriptor) ProtoMessage() {}

func (x *TaskTypeDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskTypeDescriptor.ProtoReflect.Descriptor instead.
func (*TaskTypeDescriptor) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *TaskTypeDescriptor) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskTypeDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *TaskTypeDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskTypeDescriptor) GetPayloadSchema() string {
	if x != nil {
		return x.PayloadSchema
	}
	return ""
}

func (x *TaskTypeDescriptor) GetDefaultCron() string {
	if x != nil {
		return x.DefaultCron
	}
	return ""
}

func (x *TaskTypeDescriptor) GetDefaultMaxRetry() int32 {
	if x != nil {
		return x.DefaultMaxRetry
	}
	return 0
}

func (x *TaskTypeDescriptor) GetScope() TaskScope {
	if x != nil {
		return x.Scope
	}
	return TaskScope_TASK_SCOPE_UNSPECIFIED
}

type RegisterTaskTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskTypes     []*TaskTypeDescriptor  `protobuf:"bytes,2,rep,name=task_types,json=taskTypes,proto3" json:"task_types,omitempty"` // 1..50
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTaskTypesRequest) Reset() {
	*x = RegisterTaskTypesRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTaskTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskTypesRequest) ProtoMessage() {}

func (x *RegisterTaskTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskTypesRequest.ProtoReflect.Descriptor instead.
func (*RegisterTaskTypesRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterTaskTypesRequest) GetTaskTypes() []*TaskTypeDescriptor {
	if x != nil {
		return x.TaskTypes
	}
	return nil
}

type RegisterTaskTypesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RegisteredCount  int32                  `protobuf:"varint,1,opt,name=registered_count,json=registeredCount,proto3" json:"registered_count,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RevalidatedTasks int32                  `protobuf:"varint,3,opt,name=revalidated_tasks,json=revalidatedTasks,proto3" json:"revalidated_tasks,omitempty"` // tasks re-checked because a schema changed
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterTaskTypesResponse) Reset() {
	*x = RegisterTaskTypesResponse{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTaskTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskTypesResponse) ProtoMessage() {}

func (x *RegisterTaskTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskTypesResponse.ProtoReflect.Descriptor instead.
func (*RegisterTaskTypesResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterTaskTypesResponse) GetRegisteredCount() int32 {
	if x != nil {
		return x.RegisteredCount
	}
	return 0
}

func (x *RegisterTaskTypesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterTaskTypesResponse) GetRevalidatedTasks() int32 {
	if x != nil {
		return x.RevalidatedTasks
	}
	return 0
}

type UnregisterTaskTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterTaskTypesRequest) Reset() {
	*x = UnregisterTaskTypesRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterTaskTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterTaskTypesRequest) ProtoMessage() {}

func (x *UnregisterTaskTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterTaskTypesRequest.ProtoReflect.Descriptor instead.
func (*UnregisterTaskTypesRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{3}
}

type UnregisterTaskTypesResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Message           string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	UnregisteredCount int32                  `protobuf:"varint,2,opt,name=unregistered_count,json=unregisteredCount,proto3" json:"unregistered_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnregisterTaskTypesResponse) Reset() {
	*x = UnregisterTaskTypesResponse{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterTaskTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterTaskTypesResponse) ProtoMessage() {}

func (x *UnregisterTaskTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterTaskTypesResponse.ProtoReflect.Descriptor instead.
func (*UnregisterTaskTypesResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterTaskTypesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UnregisterTaskTypesResponse) GetUnregisteredCount() int32 {
	if x != nil {
		return x.UnregisteredCount
	}
	return 0
}

// ExecuteTaskRequest carries everything the module needs for one attempt.
type ExecuteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId   string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"` // uuid, unique per attempt
	TaskType      string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`  // JSON object, <= 64 KiB, validated by the scheduler against the type schema
	Attempt       int32                  `protobuf:"varint,4,opt,name=attempt,proto3" json:"attempt,omitempty"` // 1-based
	MaxAttempts   int32                  `protobuf:"varint,5,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`    // intended occurrence time, not dispatch time
	TenantId      string                 `protobuf:"bytes,12,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`             // uuid; empty only for platform-scoped types
	TaskId        string                 `protobuf:"bytes,13,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                   // uuid of the scheduler task
	OccurrenceId  string                 `protobuf:"bytes,14,opt,name=occurrence_id,json=occurrenceId,proto3" json:"occurrence_id,omitempty"` // uuid shared by the attempts of one occurrence (idempotency key)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTaskRequest) Reset() {
	*x = ExecuteTaskRequest{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskRequest) ProtoMessage() {}

func (x *ExecuteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTaskRequest) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{5}
}

func (x *ExecuteTaskRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ExecuteTaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *ExecuteTaskRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExecuteTaskRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ExecuteTaskRequest) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *ExecuteTaskRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *ExecuteTaskRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ExecuteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteTaskRequest) GetOccurrenceId() string {
	if x != nil {
		return x.OccurrenceId
	}
	return ""
}

// ExecuteTaskResponse reports the outcome of one attempt.
type ExecuteTaskResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                            // shown in the history, <= 4 KiB (longer is cut)
	ResultData       []byte                 `protobuf:"bytes,3,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`                    // optional JSON, <= 64 KiB (longer is truncated and flagged)
	PermanentFailure bool                   `protobuf:"varint,4,opt,name=permanent_failure,json=permanentFailure,proto3" json:"permanent_failure,omitempty"` // do not retry even if attempts remain
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecuteTaskResponse) Reset() {
	*x = ExecuteTaskResponse{}
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTaskResponse) ProtoMessage() {}

func (x *ExecuteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scheduler_v1_scheduler_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTaskResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTaskResponse) Descriptor() ([]byte, []int) {
	return file_scheduler_v1_scheduler_proto_rawDescGZIP(), []int{6}
}

func (x *ExecuteTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecuteTaskResponse) GetResultData() []byte {
	if x != nil {
		return x.ResultData
	}
	return nil
}

func (x *ExecuteTaskResponse) GetPermanentFailure() bool {
	if x != nil {
		return x.PermanentFailure
	}
	return false
}

var File_scheduler_v1_scheduler_proto protoreflect.FileDescriptor

const file_scheduler_v1_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x1cscheduler/v1/scheduler.proto\x12\fscheduler.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9b\x02\n" +
	"\x12TaskTypeDescriptor\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\tR\btaskType\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12%\n" +
	"\x0epayload_schema\x18\x04 \x01(\tR\rpayloadSchema\x12!\n" +
	"\fdefault_cron\x18\x05 \x01(\tR\vdefaultCron\x12*\n" +
	"\x11default_max_retry\x18\x06 \x01(\x05R\x0fdefaultMaxRetry\x12-\n" +
	"\x05scope\x18\a \x01(\x0e2\x17.scheduler.v1.TaskScopeR\x05scope\"l\n" +
	"\x18RegisterTaskTypesRequest\x12?\n" +
	"\n" +
	"task_types\x18\x02 \x03(\v2 .scheduler.v1.TaskTypeDescriptorR\ttaskTypesJ\x04\b\x01\x10\x02R\tmodule_id\"\x8d\x01\n" +
	"\x19RegisterTaskTypesResponse\x12)\n" +
	"\x10registered_count\x18\x01 \x01(\x05R\x0fregisteredCount\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12+\n" +
	"\x11revalidated_tasks\x18\x03 \x01(\x05R\x10revalidatedTasks\"-\n" +
	"\x1aUnregisterTaskTypesRequestJ\x04\b\x01\x10\x02R\tmodule_id\"f\n" +
	"\x1bUnregisterTaskTypesResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12-\n" +
	"\x12unregistered_count\x18\x02 \x01(\x05R\x11unregisteredCount\"\xcb\x02\n" +
	"\x12ExecuteTaskRequest\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x18\n" +
	"\aattempt\x18\x04 \x01(\x05R\aattempt\x12!\n" +
	"\fmax_attempts\x18\x05 \x01(\x05R\vmaxAttempts\x12=\n" +
	"\fscheduled_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12\x1b\n" +
	"\ttenant_id\x18\f \x01(\tR\btenantId\x12\x17\n" +
	"\atask_id\x18\r \x01(\tR\x06taskId\x12#\n" +
	"\roccurrence_id\x18\x0e \x01(\tR\foccurrenceIdJ\x04\b\n" +
	"\x10\v\"\x97\x01\n" +
	"\x13ExecuteTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vresult_data\x18\x03 \x01(\fR\n" +
	"resultData\x12+\n" +
	"\x11permanent_failure\x18\x04 \x01(\bR\x10permanentFailure*W\n" +
	"\tTaskScope\x12\x1a\n" +
	"\x16TASK_SCOPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TASK_SCOPE_TENANT\x10\x01\x12\x17\n" +
	"\x13TASK_SCOPE_PLATFORM\x10\x022\xe0\x01\n" +
	"\fRegistration\x12d\n" +
	"\x11RegisterTaskTypes\x12&.scheduler.v1.RegisterTaskTypesRequest\x1a'.scheduler.v1.RegisterTaskTypesResponse\x12j\n" +
	"\x13UnregisterTaskTypes\x12(.scheduler.v1.UnregisterTaskTypesRequest\x1a).scheduler.v1.UnregisterTaskTypesResponse2b\n" +
	"\fTaskExecutor\x12R\n" +
	"\vExecuteTask\x12 .scheduler.v1.ExecuteTaskRequest\x1a!.scheduler.v1.ExecuteTaskResponseBTZRgithub.com/go-tangra/go-tangra-scheduler/sdk/v4/api/proto/scheduler/v1;schedulerv1b\x06proto3"

var (
	file_scheduler_v1_scheduler_proto_rawDescOnce sync.Once
	file_scheduler_v1_scheduler_proto_rawDescData []byte
)

func file_scheduler_v1_scheduler_proto_rawDescGZIP() []byte {
	file_scheduler_v1_scheduler_proto_rawDescOnce.Do(func() {
		file_scheduler_v1_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scheduler_v1_scheduler_proto_rawDesc), len(file_scheduler_v1_scheduler_proto_rawDesc)))
	})
	return file_scheduler_v1_scheduler_proto_rawDescData
}

var file_scheduler_v1_scheduler_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_scheduler_v1_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_scheduler_v1_scheduler_proto_goTypes = []any{
	(TaskScope)(0),                      // 0: scheduler.v1.TaskScope
	(*TaskTypeDescriptor)(nil),          // 1: scheduler.v1.TaskTypeDescriptor
	(*RegisterTaskTypesRequest)(nil),    // 2: scheduler.v1.RegisterTaskTypesRequest
	(*RegisterTaskTypesResponse)(nil),   // 3: scheduler.v1.RegisterTaskTypesResponse
	(*UnregisterTaskTypesRequest)(nil),  // 4: scheduler.v1.UnregisterTaskTypesRequest
	(*UnregisterTaskTypesResponse)(nil), // 5: scheduler.v1.UnregisterTaskTypesResponse
	(*ExecuteTaskRequest)(nil),          // 6: scheduler.v1.ExecuteTaskRequest
	(*ExecuteTaskResponse)(nil),         // 7: scheduler.v1.ExecuteTaskResponse
	(*timestamppb.Timestamp)(nil),       // 8: google.protobuf.Timestamp
}
var file_scheduler_v1_scheduler_proto_depIdxs = []int32{
	0, // 0: scheduler.v1.TaskTypeDescriptor.scope:type_name -> scheduler.v1.TaskScope
	1, // 1: scheduler.v1.RegisterTaskTypesRequest.task_types:type_name -> scheduler.v1.TaskTypeDescriptor
	8, // 2: scheduler.v1.ExecuteTaskRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	2, // 3: scheduler.v1.Registration.RegisterTaskTypes:input_type -> scheduler.v1.RegisterTaskTypesRequest
	4, // 4: scheduler.v1.Registration.UnregisterTaskTypes:input_type -> scheduler.v1.UnregisterTaskTypesRequest
	6, // 5: scheduler.v1.TaskExecutor.ExecuteTask:input_type -> scheduler.v1.ExecuteTaskRequest
	3, // 6: scheduler.v1.Registration.RegisterTaskTypes:output_type -> scheduler.v1.RegisterTaskTypesResponse
	5, // 7: scheduler.v1.Registration.UnregisterTaskTypes:output_type -> scheduler.v1.UnregisterTaskTypesResponse
	7, // 8: scheduler.v1.TaskExecutor.ExecuteTask:output_type -> scheduler.v1.ExecuteTaskResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_scheduler_v1_scheduler_proto_init() }
func file_scheduler_v1_scheduler_proto_init() {
	if File_scheduler_v1_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scheduler_v1_scheduler_proto_rawDesc), len(file_scheduler_v1_scheduler_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_scheduler_v1_scheduler_proto_goTypes,
		DependencyIndexes: file_scheduler_v1_scheduler_proto_depIdxs,
		EnumInfos:         file_scheduler_v1_scheduler_proto_enumTypes,
		MessageInfos:      file_scheduler_v1_scheduler_proto_msgTypes,
	}.Build()
	File_scheduler_v1_scheduler_proto = out.File
	file_scheduler_v1_scheduler_proto_goTypes = nil
	file_scheduler_v1_scheduler_proto_depIdxs = nil
}
