// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: scheduler/v1/scheduler.proto

// Service-to-service contract of the scheduler module (feature 026). Reached
// only over the Freya SPIFFE mTLS channel; nothing here is proxied by the
// gateway.
//
//   - Registration is served by the scheduler and called by the modules that
//     execute tasks. The owning module is the caller's verified SPIFFE
//     identity (spiffe://<td>/svc/<module>), never a request field; every type
//     name must start with "<module>:". The scheduler's policy.yaml lists the
//     modules allowed to call it.
//   - TaskExecutor is served by every module that executes tasks and called by
//     the scheduler only: each module's policy.yaml allows
//     spiffe://<td>/svc/scheduler (and nobody else) to call ExecuteTask, and
//     the module re-checks the peer (sdk pkg/taskexec).
//
// The messages keep the fields of the v3 go-tangra-common contract
// (common.service.v1) where their meaning is unchanged; v4 tenants are UUIDs.

package schedulerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Registration_RegisterTaskTypes_FullMethodName   = "/scheduler.v1.Registration/RegisterTaskTypes"
	Registration_UnregisterTaskTypes_FullMethodName = "/scheduler.v1.Registration/UnregisterTaskTypes"
)

// RegistrationClient is the client API for Registration service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegistrationClient interface {
	// RegisterTaskTypes declares (or updates) the task types the calling module
	// executes. Idempotent; a registered type becomes available again. Refused
	// as a whole (PERMISSION_DENIED) when a name is outside the caller's
	// namespace or owned by another module, and (INVALID_ARGUMENT) when a
	// descriptor is malformed (limits in research D4).
	RegisterTaskTypes(ctx context.Context, in *RegisterTaskTypesRequest, opts ...grpc.CallOption) (*RegisterTaskTypesResponse, error)
	// UnregisterTaskTypes marks every type of the calling module unavailable.
	// Tasks are kept (shown "type unavailable", occurrences skipped) until the
	// module registers again.
	UnregisterTaskTypes(ctx context.Context, in *UnregisterTaskTypesRequest, opts ...grpc.CallOption) (*UnregisterTaskTypesResponse, error)
}

type registrationClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistrationClient(cc grpc.ClientConnInterface) RegistrationClient {
	return &registrationClient{cc}
}

func (c *registrationClient) RegisterTaskTypes(ctx context.Context, in *RegisterTaskTypesRequest, opts ...grpc.CallOption) (*RegisterTaskTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTaskTypesResponse)
	err := c.cc.Invoke(ctx, Registration_RegisterTaskTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *registrationClient) UnregisterTaskTypes(ctx context.Context, in *UnregisterTaskTypesRequest, opts ...grpc.CallOption) (*UnregisterTaskTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterTaskTypesResponse)
	err := c.cc.Invoke(ctx, Registration_UnregisterTaskTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationServer is the server API for Registration service.
// All implementations must embed UnimplementedRegistrationServer
// for forward compatibility.
type RegistrationServer interface {
	// RegisterTaskTypes declares (or updates) the task types the calling module
	// executes. Idempotent; a registered type becomes available again. Refused
	// as a whole (PERMISSION_DENIED) when a name is outside the caller's
	// namespace or owned by another module, and (INVALID_ARGUMENT) when a
	// descriptor is malformed (limits in research D4).
	RegisterTaskTypes(context.Context, *RegisterTaskTypesRequest) (*RegisterTaskTypesResponse, error)
	// UnregisterTaskTypes marks every type of the calling module unavailable.
	// Tasks are kept (shown "type unavailable", occurrences skipped) until the
	// module registers again.
	UnregisterTaskTypes(context.Context, *UnregisterTaskTypesRequest) (*UnregisterTaskTypesResponse, error)
	mustEmbedUnimplementedRegistrationServer()
}

// UnimplementedRegistrationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRegistrationServer struct{}

func (UnimplementedRegistrationServer) RegisterTaskTypes(context.Context, *RegisterTaskTypesRequest) (*RegisterTaskTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTaskTypes not implemented")
}
func (UnimplementedRegistrationServer) UnregisterTaskTypes(context.Context, *UnregisterTaskTypesRequest) (*UnregisterTaskTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnregisterTaskTypes not implemented")
}
func (UnimplementedRegistrationServer) mustEmbedUnimplementedRegistrationServer() {}
func (UnimplementedRegistrationServer) testEmbeddedByValue()                      {}

// UnsafeRegistrationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegistrationServer will
// result in compilation errors.
type UnsafeRegistrationServer interface {
	mustEmbedUnimplementedRegistrationServer()
}

func RegisterRegistrationServer(s grpc.ServiceRegistrar, srv RegistrationServer) {
	// If the following call panics, it indicates UnimplementedRegistrationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Registration_ServiceDesc, srv)
}

func _Registration_RegisterTaskTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTaskTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).RegisterTaskTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registration_RegisterTaskTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).RegisterTaskTypes(ctx, req.(*RegisterTaskTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Registration_UnregisterTaskTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterTaskTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationServer).UnregisterTaskTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Registration_UnregisterTaskTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationServer).UnregisterTaskTypes(ctx, req.(*UnregisterTaskTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Registration_ServiceDesc is the grpc.ServiceDesc for Registration service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Registration_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.v1.Registration",
	HandlerType: (*RegistrationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTaskTypes",
			Handler:    _Registration_RegisterTaskTypes_Handler,
		},
		{
			MethodName: "UnregisterTaskTypes",
			Handler:    _Registration_UnregisterTaskTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduler/v1/scheduler.proto",
}

const (
	TaskExecutor_ExecuteTask_FullMethodName = "/scheduler.v1.TaskExecutor/ExecuteTask"
)

// TaskExecutorClient is the client API for TaskExecutor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskExecutorClient interface {
	// ExecuteTask runs one attempt of a task occurrence in the owning module.
	// The module scopes all work to tenant_id (empty only for its own
	// platform-scoped types), validates the payload again and answers
	// promptly: long work is queued and reported in message. Transport errors
	// and success=false without permanent_failure are retried by the scheduler.
	ExecuteTask(ctx context.Context, in *ExecuteTaskRequest, opts ...grpc.CallOption) (*ExecuteTaskResponse, error)
}

type taskExecutorClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskExecutorClient(cc grpc.ClientConnInterface) TaskExecutorClient {
	return &taskExecutorClient{cc}
}

func (c *taskExecutorClient) ExecuteTask(ctx context.Context, in *ExecuteTaskRequest, opts ...grpc.CallOption) (*ExecuteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteTaskResponse)
	err := c.cc.Invoke(ctx, TaskExecutor_ExecuteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskExecutorServer is the server API for TaskExecutor service.
// All implementations must embed UnimplementedTaskExecutorServer
// for forward compatibility.
type TaskExecutorServer interface {
	// ExecuteTask runs one attempt of a task occurrence in the owning module.
	// The module scopes all work to tenant_id (empty only for its own
	// platform-scoped types), validates the payload again and answers
	// promptly: long work is queued and reported in message. Transport errors
	// and success=false without permanent_failure are retried by the scheduler.
	ExecuteTask(context.Context, *ExecuteTaskRequest) (*ExecuteTaskResponse, error)
	mustEmbedUnimplementedTaskExecutorServer()
}

// UnimplementedTaskExecutorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskExecutorServer struct{}

func (UnimplementedTaskExecutorServer) ExecuteTask(context.Context, *ExecuteTaskRequest) (*ExecuteTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteTask not implemented")
}
func (UnimplementedTaskExecutorServer) mustEmbedUnimplementedTaskExecutorServer() {}
func (UnimplementedTaskExecutorServer) testEmbeddedByValue()                      {}

// UnsafeTaskExecutorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskExecutorServer will
// result in compilation errors.
type UnsafeTaskExecutorServer interface {
	mustEmbedUnimplementedTaskExecutorServer()
}

func RegisterTaskExecutorServer(s grpc.ServiceRegistrar, srv TaskExecutorServer) {
	// If the following call panics, it indicates UnimplementedTaskExecutorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskExecutor_ServiceDesc, srv)
}

func _TaskExecutor_ExecuteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskExecutorServer).ExecuteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskExecutor_ExecuteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskExecutorServer).ExecuteTask(ctx, req.(*ExecuteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskExecutor_ServiceDesc is the grpc.ServiceDesc for TaskExecutor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskExecutor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scheduler.v1.TaskExecutor",
	HandlerType: (*TaskExecutorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteTask",
			Handler:    _TaskExecutor_ExecuteTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheduler/v1/scheduler.proto",
}
