// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"
	"time"

	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/schema"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/task"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/taskexecution"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/tasktype"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskMixin := schema.Task{}.Mixin()
	task.Policy = privacy.NewPolicies(taskMixin[4], schema.Task{})
	task.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := task.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskMixinFields4 := taskMixin[4].Fields()
	_ = taskMixinFields4
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescTenantID is the schema descriptor for tenant_id field.
	taskDescTenantID := taskMixinFields4[0].Descriptor()
	// task.DefaultTenantID holds the default value on creation for the tenant_id field.
	task.DefaultTenantID = taskDescTenantID.Default.(uint32)
	// taskDescEnable is the schema descriptor for enable field.
	taskDescEnable := taskFields[6].Descriptor()
	// task.DefaultEnable holds the default value on creation for the enable field.
	task.DefaultEnable = taskDescEnable.Default.(bool)
	// taskDescRunCount is the schema descriptor for run_count field.
	taskDescRunCount := taskFields[10].Descriptor()
	// task.DefaultRunCount holds the default value on creation for the run_count field.
	task.DefaultRunCount = taskDescRunCount.Default.(int32)
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskMixinFields0[0].Descriptor()
	// task.IDValidator is a validator for the "id" field. It is called by the builders before save.
	task.IDValidator = taskDescID.Validators[0].(func(uint32) error)
	taskexecutionMixin := schema.TaskExecution{}.Mixin()
	taskexecutionMixinFields0 := taskexecutionMixin[0].Fields()
	_ = taskexecutionMixinFields0
	taskexecutionFields := schema.TaskExecution{}.Fields()
	_ = taskexecutionFields
	// taskexecutionDescExecutionID is the schema descriptor for execution_id field.
	taskexecutionDescExecutionID := taskexecutionFields[0].Descriptor()
	// taskexecution.ExecutionIDValidator is a validator for the "execution_id" field. It is called by the builders before save.
	taskexecution.ExecutionIDValidator = taskexecutionDescExecutionID.Validators[0].(func(string) error)
	// taskexecutionDescTaskType is the schema descriptor for task_type field.
	taskexecutionDescTaskType := taskexecutionFields[1].Descriptor()
	// taskexecution.TaskTypeValidator is a validator for the "task_type" field. It is called by the builders before save.
	taskexecution.TaskTypeValidator = taskexecutionDescTaskType.Validators[0].(func(string) error)
	// taskexecutionDescModuleID is the schema descriptor for module_id field.
	taskexecutionDescModuleID := taskexecutionFields[2].Descriptor()
	// taskexecution.ModuleIDValidator is a validator for the "module_id" field. It is called by the builders before save.
	taskexecution.ModuleIDValidator = taskexecutionDescModuleID.Validators[0].(func(string) error)
	// taskexecutionDescStatus is the schema descriptor for status field.
	taskexecutionDescStatus := taskexecutionFields[3].Descriptor()
	// taskexecution.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	taskexecution.StatusValidator = taskexecutionDescStatus.Validators[0].(func(string) error)
	// taskexecutionDescAttempt is the schema descriptor for attempt field.
	taskexecutionDescAttempt := taskexecutionFields[5].Descriptor()
	// taskexecution.DefaultAttempt holds the default value on creation for the attempt field.
	taskexecution.DefaultAttempt = taskexecutionDescAttempt.Default.(int32)
	// taskexecutionDescDurationMs is the schema descriptor for duration_ms field.
	taskexecutionDescDurationMs := taskexecutionFields[6].Descriptor()
	// taskexecution.DefaultDurationMs holds the default value on creation for the duration_ms field.
	taskexecution.DefaultDurationMs = taskexecutionDescDurationMs.Default.(int64)
	// taskexecutionDescStartedAt is the schema descriptor for started_at field.
	taskexecutionDescStartedAt := taskexecutionFields[7].Descriptor()
	// taskexecution.DefaultStartedAt holds the default value on creation for the started_at field.
	taskexecution.DefaultStartedAt = taskexecutionDescStartedAt.Default.(func() time.Time)
	// taskexecutionDescTenantID is the schema descriptor for tenant_id field.
	taskexecutionDescTenantID := taskexecutionFields[9].Descriptor()
	// taskexecution.DefaultTenantID holds the default value on creation for the tenant_id field.
	taskexecution.DefaultTenantID = taskexecutionDescTenantID.Default.(uint32)
	// taskexecutionDescID is the schema descriptor for id field.
	taskexecutionDescID := taskexecutionMixinFields0[0].Descriptor()
	// taskexecution.IDValidator is a validator for the "id" field. It is called by the builders before save.
	taskexecution.IDValidator = taskexecutionDescID.Validators[0].(func(uint32) error)
	tasktypeFields := schema.TaskType{}.Fields()
	_ = tasktypeFields
	// tasktypeDescTaskType is the schema descriptor for task_type field.
	tasktypeDescTaskType := tasktypeFields[0].Descriptor()
	// tasktype.TaskTypeValidator is a validator for the "task_type" field. It is called by the builders before save.
	tasktype.TaskTypeValidator = tasktypeDescTaskType.Validators[0].(func(string) error)
	// tasktypeDescModuleID is the schema descriptor for module_id field.
	tasktypeDescModuleID := tasktypeFields[1].Descriptor()
	// tasktype.ModuleIDValidator is a validator for the "module_id" field. It is called by the builders before save.
	tasktype.ModuleIDValidator = tasktypeDescModuleID.Validators[0].(func(string) error)
	// tasktypeDescDefaultMaxRetry is the schema descriptor for default_max_retry field.
	tasktypeDescDefaultMaxRetry := tasktypeFields[6].Descriptor()
	// tasktype.DefaultDefaultMaxRetry holds the default value on creation for the default_max_retry field.
	tasktype.DefaultDefaultMaxRetry = tasktypeDescDefaultMaxRetry.Default.(int32)
	// tasktypeDescRegisteredAt is the schema descriptor for registered_at field.
	tasktypeDescRegisteredAt := tasktypeFields[7].Descriptor()
	// tasktype.DefaultRegisteredAt holds the default value on creation for the registered_at field.
	tasktype.DefaultRegisteredAt = tasktypeDescRegisteredAt.Default.(func() time.Time)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
