// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/task"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/taskexecution"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/tasktype"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Task is the client for interacting with the Task builders.
	Task *TaskClient
	// TaskExecution is the client for interacting with the TaskExecution builders.
	TaskExecution *TaskExecutionClient
	// TaskType is the client for interacting with the TaskType builders.
	TaskType *TaskTypeClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Task = NewTaskClient(c.config)
	c.TaskExecution = NewTaskExecutionClient(c.config)
	c.TaskType = NewTaskTypeClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Task:          NewTaskClient(cfg),
		TaskExecution: NewTaskExecutionClient(cfg),
		TaskType:      NewTaskTypeClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:           ctx,
		config:        cfg,
		Task:          NewTaskClient(cfg),
		TaskExecution: NewTaskExecutionClient(cfg),
		TaskType:      NewTaskTypeClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Task.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Task.Use(hooks...)
	c.TaskExecution.Use(hooks...)
	c.TaskType.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Task.Intercept(interceptors...)
	c.TaskExecution.Intercept(interceptors...)
	c.TaskType.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *TaskMutation:
		return c.Task.mutate(ctx, m)
	case *TaskExecutionMutation:
		return c.TaskExecution.mutate(ctx, m)
	case *TaskTypeMutation:
		return c.TaskType.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// TaskClient is a client for the Task schema.
type TaskClient struct {
	config
}

// NewTaskClient returns a client for the Task from the given config.
func NewTaskClient(c config) *TaskClient {
	return &TaskClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `task.Hooks(f(g(h())))`.
func (c *TaskClient) Use(hooks ...Hook) {
	c.hooks.Task = append(c.hooks.Task, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `task.Intercept(f(g(h())))`.
func (c *TaskClient) Intercept(interceptors ...Interceptor) {
	c.inters.Task = append(c.inters.Task, interceptors...)
}

// Create returns a builder for creating a Task entity.
func (c *TaskClient) Create() *TaskCreate {
	mutation := newTaskMutation(c.config, OpCreate)
	return &TaskCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Task entities.
func (c *TaskClient) CreateBulk(builders ...*TaskCreate) *TaskCreateBulk {
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskClient) MapCreateBulk(slice any, setFunc func(*TaskCreate, int)) *TaskCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskCreateBulk{err: fmt.Errorf("calling to TaskClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Task.
func (c *TaskClient) Update() *TaskUpdate {
	mutation := newTaskMutation(c.config, OpUpdate)
	return &TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskClient) UpdateOne(_m *Task) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTask(_m))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskClient) UpdateOneID(id uint32) *TaskUpdateOne {
	mutation := newTaskMutation(c.config, OpUpdateOne, withTaskID(id))
	return &TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Task.
func (c *TaskClient) Delete() *TaskDelete {
	mutation := newTaskMutation(c.config, OpDelete)
	return &TaskDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskClient) DeleteOne(_m *Task) *TaskDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskClient) DeleteOneID(id uint32) *TaskDeleteOne {
	builder := c.Delete().Where(task.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskDeleteOne{builder}
}

// Query returns a query builder for Task.
func (c *TaskClient) Query() *TaskQuery {
	return &TaskQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTask},
		inters: c.Interceptors(),
	}
}

// Get returns a Task entity by its id.
func (c *TaskClient) Get(ctx context.Context, id uint32) (*Task, error) {
	return c.Query().Where(task.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskClient) GetX(ctx context.Context, id uint32) *Task {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TaskClient) Hooks() []Hook {
	hooks := c.hooks.Task
	return append(hooks[:len(hooks):len(hooks)], task.Hooks[:]...)
}

// Interceptors returns the client interceptors.
func (c *TaskClient) Interceptors() []Interceptor {
	return c.inters.Task
}

func (c *TaskClient) mutate(ctx context.Context, m *TaskMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Task mutation op: %q", m.Op())
	}
}

// TaskExecutionClient is a client for the TaskExecution schema.
type TaskExecutionClient struct {
	config
}

// NewTaskExecutionClient returns a client for the TaskExecution from the given config.
func NewTaskExecutionClient(c config) *TaskExecutionClient {
	return &TaskExecutionClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `taskexecution.Hooks(f(g(h())))`.
func (c *TaskExecutionClient) Use(hooks ...Hook) {
	c.hooks.TaskExecution = append(c.hooks.TaskExecution, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `taskexecution.Intercept(f(g(h())))`.
func (c *TaskExecutionClient) Intercept(interceptors ...Interceptor) {
	c.inters.TaskExecution = append(c.inters.TaskExecution, interceptors...)
}

// Create returns a builder for creating a TaskExecution entity.
func (c *TaskExecutionClient) Create() *TaskExecutionCreate {
	mutation := newTaskExecutionMutation(c.config, OpCreate)
	return &TaskExecutionCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TaskExecution entities.
func (c *TaskExecutionClient) CreateBulk(builders ...*TaskExecutionCreate) *TaskExecutionCreateBulk {
	return &TaskExecutionCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskExecutionClient) MapCreateBulk(slice any, setFunc func(*TaskExecutionCreate, int)) *TaskExecutionCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskExecutionCreateBulk{err: fmt.Errorf("calling to TaskExecutionClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskExecutionCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskExecutionCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TaskExecution.
func (c *TaskExecutionClient) Update() *TaskExecutionUpdate {
	mutation := newTaskExecutionMutation(c.config, OpUpdate)
	return &TaskExecutionUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskExecutionClient) UpdateOne(_m *TaskExecution) *TaskExecutionUpdateOne {
	mutation := newTaskExecutionMutation(c.config, OpUpdateOne, withTaskExecution(_m))
	return &TaskExecutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskExecutionClient) UpdateOneID(id uint32) *TaskExecutionUpdateOne {
	mutation := newTaskExecutionMutation(c.config, OpUpdateOne, withTaskExecutionID(id))
	return &TaskExecutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TaskExecution.
func (c *TaskExecutionClient) Delete() *TaskExecutionDelete {
	mutation := newTaskExecutionMutation(c.config, OpDelete)
	return &TaskExecutionDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskExecutionClient) DeleteOne(_m *TaskExecution) *TaskExecutionDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskExecutionClient) DeleteOneID(id uint32) *TaskExecutionDeleteOne {
	builder := c.Delete().Where(taskexecution.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskExecutionDeleteOne{builder}
}

// Query returns a query builder for TaskExecution.
func (c *TaskExecutionClient) Query() *TaskExecutionQuery {
	return &TaskExecutionQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTaskExecution},
		inters: c.Interceptors(),
	}
}

// Get returns a TaskExecution entity by its id.
func (c *TaskExecutionClient) Get(ctx context.Context, id uint32) (*TaskExecution, error) {
	return c.Query().Where(taskexecution.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskExecutionClient) GetX(ctx context.Context, id uint32) *TaskExecution {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TaskExecutionClient) Hooks() []Hook {
	return c.hooks.TaskExecution
}

// Interceptors returns the client interceptors.
func (c *TaskExecutionClient) Interceptors() []Interceptor {
	return c.inters.TaskExecution
}

func (c *TaskExecutionClient) mutate(ctx context.Context, m *TaskExecutionMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskExecutionCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskExecutionUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskExecutionUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskExecutionDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TaskExecution mutation op: %q", m.Op())
	}
}

// TaskTypeClient is a client for the TaskType schema.
type TaskTypeClient struct {
	config
}

// NewTaskTypeClient returns a client for the TaskType from the given config.
func NewTaskTypeClient(c config) *TaskTypeClient {
	return &TaskTypeClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tasktype.Hooks(f(g(h())))`.
func (c *TaskTypeClient) Use(hooks ...Hook) {
	c.hooks.TaskType = append(c.hooks.TaskType, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tasktype.Intercept(f(g(h())))`.
func (c *TaskTypeClient) Intercept(interceptors ...Interceptor) {
	c.inters.TaskType = append(c.inters.TaskType, interceptors...)
}

// Create returns a builder for creating a TaskType entity.
func (c *TaskTypeClient) Create() *TaskTypeCreate {
	mutation := newTaskTypeMutation(c.config, OpCreate)
	return &TaskTypeCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of TaskType entities.
func (c *TaskTypeClient) CreateBulk(builders ...*TaskTypeCreate) *TaskTypeCreateBulk {
	return &TaskTypeCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TaskTypeClient) MapCreateBulk(slice any, setFunc func(*TaskTypeCreate, int)) *TaskTypeCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TaskTypeCreateBulk{err: fmt.Errorf("calling to TaskTypeClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TaskTypeCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TaskTypeCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for TaskType.
func (c *TaskTypeClient) Update() *TaskTypeUpdate {
	mutation := newTaskTypeMutation(c.config, OpUpdate)
	return &TaskTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TaskTypeClient) UpdateOne(_m *TaskType) *TaskTypeUpdateOne {
	mutation := newTaskTypeMutation(c.config, OpUpdateOne, withTaskType(_m))
	return &TaskTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TaskTypeClient) UpdateOneID(id int) *TaskTypeUpdateOne {
	mutation := newTaskTypeMutation(c.config, OpUpdateOne, withTaskTypeID(id))
	return &TaskTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for TaskType.
func (c *TaskTypeClient) Delete() *TaskTypeDelete {
	mutation := newTaskTypeMutation(c.config, OpDelete)
	return &TaskTypeDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TaskTypeClient) DeleteOne(_m *TaskType) *TaskTypeDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TaskTypeClient) DeleteOneID(id int) *TaskTypeDeleteOne {
	builder := c.Delete().Where(tasktype.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TaskTypeDeleteOne{builder}
}

// Query returns a query builder for TaskType.
func (c *TaskTypeClient) Query() *TaskTypeQuery {
	return &TaskTypeQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTaskType},
		inters: c.Interceptors(),
	}
}

// Get returns a TaskType entity by its id.
func (c *TaskTypeClient) Get(ctx context.Context, id int) (*TaskType, error) {
	return c.Query().Where(tasktype.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TaskTypeClient) GetX(ctx context.Context, id int) *TaskType {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TaskTypeClient) Hooks() []Hook {
	return c.hooks.TaskType
}

// Interceptors returns the client interceptors.
func (c *TaskTypeClient) Interceptors() []Interceptor {
	return c.inters.TaskType
}

func (c *TaskTypeClient) mutate(ctx context.Context, m *TaskTypeMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TaskTypeCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TaskTypeUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TaskTypeUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TaskTypeDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown TaskType mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Task, TaskExecution, TaskType []ent.Hook
	}
	inters struct {
		Task, TaskExecution, TaskType []ent.Interceptor
	}
)
