// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/tasktype"
)

// TaskTypeCreate is the builder for creating a TaskType entity.
type TaskTypeCreate struct {
	config
	mutation *TaskTypeMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTaskType sets the "task_type" field.
func (_c *TaskTypeCreate) SetTaskType(v string) *TaskTypeCreate {
	_c.mutation.SetTaskType(v)
	return _c
}

// SetModuleID sets the "module_id" field.
func (_c *TaskTypeCreate) SetModuleID(v string) *TaskTypeCreate {
	_c.mutation.SetModuleID(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *TaskTypeCreate) SetDisplayName(v string) *TaskTypeCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *TaskTypeCreate) SetNillableDisplayName(v *string) *TaskTypeCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *TaskTypeCreate) SetDescription(v string) *TaskTypeCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *TaskTypeCreate) SetNillableDescription(v *string) *TaskTypeCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetPayloadSchema sets the "payload_schema" field.
func (_c *TaskTypeCreate) SetPayloadSchema(v string) *TaskTypeCreate {
	_c.mutation.SetPayloadSchema(v)
	return _c
}

// SetNillablePayloadSchema sets the "payload_schema" field if the given value is not nil.
func (_c *TaskTypeCreate) SetNillablePayloadSchema(v *string) *TaskTypeCreate {
	if v != nil {
		_c.SetPayloadSchema(*v)
	}
	return _c
}

// SetDefaultCron sets the "default_cron" field.
func (_c *TaskTypeCreate) SetDefaultCron(v string) *TaskTypeCreate {
	_c.mutation.SetDefaultCron(v)
	return _c
}

// SetNillableDefaultCron sets the "default_cron" field if the given value is not nil.
func (_c *TaskTypeCreate) SetNillableDefaultCron(v *string) *TaskTypeCreate {
	if v != nil {
		_c.SetDefaultCron(*v)
	}
	return _c
}

// SetDefaultMaxRetry sets the "default_max_retry" field.
func (_c *TaskTypeCreate) SetDefaultMaxRetry(v int32) *TaskTypeCreate {
	_c.mutation.SetDefaultMaxRetry(v)
	return _c
}

// SetNillableDefaultMaxRetry sets the "default_max_retry" field if the given value is not nil.
func (_c *TaskTypeCreate) SetNillableDefaultMaxRetry(v *int32) *TaskTypeCreate {
	if v != nil {
		_c.SetDefaultMaxRetry(*v)
	}
	return _c
}

// SetRegisteredAt sets the "registered_at" field.
func (_c *TaskTypeCreate) SetRegisteredAt(v time.Time) *TaskTypeCreate {
	_c.mutation.SetRegisteredAt(v)
	return _c
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (_c *TaskTypeCreate) SetNillableRegisteredAt(v *time.Time) *TaskTypeCreate {
	if v != nil {
		_c.SetRegisteredAt(*v)
	}
	return _c
}

// Mutation returns the TaskTypeMutation object of the builder.
func (_c *TaskTypeCreate) Mutation() *TaskTypeMutation {
	return _c.mutation
}

// Save creates the TaskType in the database.
func (_c *TaskTypeCreate) Save(ctx context.Context) (*TaskType, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskTypeCreate) SaveX(ctx context.Context) *TaskType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskTypeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskTypeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskTypeCreate) defaults() {
	if _, ok := _c.mutation.DefaultMaxRetry(); !ok {
		v := tasktype.DefaultDefaultMaxRetry
		_c.mutation.SetDefaultMaxRetry(v)
	}
	if _, ok := _c.mutation.RegisteredAt(); !ok {
		v := tasktype.DefaultRegisteredAt()
		_c.mutation.SetRegisteredAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskTypeCreate) check() error {
	if _, ok := _c.mutation.TaskType(); !ok {
		return &ValidationError{Name: "task_type", err: errors.New(`ent: missing required field "TaskType.task_type"`)}
	}
	if v, ok := _c.mutation.TaskType(); ok {
		if err := tasktype.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "TaskType.task_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModuleID(); !ok {
		return &ValidationError{Name: "module_id", err: errors.New(`ent: missing required field "TaskType.module_id"`)}
	}
	if v, ok := _c.mutation.ModuleID(); ok {
		if err := tasktype.ModuleIDValidator(v); err != nil {
			return &ValidationError{Name: "module_id", err: fmt.Errorf(`ent: validator failed for field "TaskType.module_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DefaultMaxRetry(); !ok {
		return &ValidationError{Name: "default_max_retry", err: errors.New(`ent: missing required field "TaskType.default_max_retry"`)}
	}
	if _, ok := _c.mutation.RegisteredAt(); !ok {
		return &ValidationError{Name: "registered_at", err: errors.New(`ent: missing required field "TaskType.registered_at"`)}
	}
	return nil
}

func (_c *TaskTypeCreate) sqlSave(ctx context.Context) (*TaskType, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskTypeCreate) createSpec() (*TaskType, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskType{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(tasktype.Table, sqlgraph.NewFieldSpec(tasktype.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TaskType(); ok {
		_spec.SetField(tasktype.FieldTaskType, field.TypeString, value)
		_node.TaskType = value
	}
	if value, ok := _c.mutation.ModuleID(); ok {
		_spec.SetField(tasktype.FieldModuleID, field.TypeString, value)
		_node.ModuleID = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(tasktype.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = &value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(tasktype.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.PayloadSchema(); ok {
		_spec.SetField(tasktype.FieldPayloadSchema, field.TypeString, value)
		_node.PayloadSchema = &value
	}
	if value, ok := _c.mutation.DefaultCron(); ok {
		_spec.SetField(tasktype.FieldDefaultCron, field.TypeString, value)
		_node.DefaultCron = &value
	}
	if value, ok := _c.mutation.DefaultMaxRetry(); ok {
		_spec.SetField(tasktype.FieldDefaultMaxRetry, field.TypeInt32, value)
		_node.DefaultMaxRetry = value
	}
	if value, ok := _c.mutation.RegisteredAt(); ok {
		_spec.SetField(tasktype.FieldRegisteredAt, field.TypeTime, value)
		_node.RegisteredAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskType.Create().
//		SetTaskType(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskTypeUpsert) {
//			SetTaskType(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskTypeCreate) OnConflict(opts ...sql.ConflictOption) *TaskTypeUpsertOne {
	_c.conflict = opts
	return &TaskTypeUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskType.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskTypeCreate) OnConflictColumns(columns ...string) *TaskTypeUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskTypeUpsertOne{
		create: _c,
	}
}

type (
	// TaskTypeUpsertOne is the builder for "upsert"-ing
	//  one TaskType node.
	TaskTypeUpsertOne struct {
		create *TaskTypeCreate
	}

	// TaskTypeUpsert is the "OnConflict" setter.
	TaskTypeUpsert struct {
		*sql.UpdateSet
	}
)

// SetTaskType sets the "task_type" field.
func (u *TaskTypeUpsert) SetTaskType(v string) *TaskTypeUpsert {
	u.Set(tasktype.FieldTaskType, v)
	return u
}

// UpdateTaskType sets the "task_type" field to the value that was provided on create.
func (u *TaskTypeUpsert) UpdateTaskType() *TaskTypeUpsert {
	u.SetExcluded(tasktype.FieldTaskType)
	return u
}

// SetModuleID sets the "module_id" field.
func (u *TaskTypeUpsert) SetModuleID(v string) *TaskTypeUpsert {
	u.Set(tasktype.FieldModuleID, v)
	return u
}

// UpdateModuleID sets the "module_id" field to the value that was provided on create.
func (u *TaskTypeUpsert) UpdateModuleID() *TaskTypeUpsert {
	u.SetExcluded(tasktype.FieldModuleID)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *TaskTypeUpsert) SetDisplayName(v string) *TaskTypeUpsert {
	u.Set(tasktype.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *TaskTypeUpsert) UpdateDisplayName() *TaskTypeUpsert {
	u.SetExcluded(tasktype.FieldDisplayName)
	return u
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *TaskTypeUpsert) ClearDisplayName() *TaskTypeUpsert {
	u.SetNull(tasktype.FieldDisplayName)
	return u
}

// SetDescription sets the "description" field.
func (u *TaskTypeUpsert) SetDescription(v string) *TaskTypeUpsert {
	u.Set(tasktype.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TaskTypeUpsert) UpdateDescription() *TaskTypeUpsert {
	u.SetExcluded(tasktype.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *TaskTypeUpsert) ClearDescription() *TaskTypeUpsert {
	u.SetNull(tasktype.FieldDescription)
	return u
}

// SetPayloadSchema sets the "payload_schema" field.
func (u *TaskTypeUpsert) SetPayloadSchema(v string) *TaskTypeUpsert {
	u.Set(tasktype.FieldPayloadSchema, v)
	return u
}

// UpdatePayloadSchema sets the "payload_schema" field to the value that was provided on create.
func (u *TaskTypeUpsert) UpdatePayloadSchema() *TaskTypeUpsert {
	u.SetExcluded(tasktype.FieldPayloadSchema)
	return u
}

// ClearPayloadSchema clears the value of the "payload_schema" field.
func (u *TaskTypeUpsert) ClearPayloadSchema() *TaskTypeUpsert {
	u.SetNull(tasktype.FieldPayloadSchema)
	return u
}

// SetDefaultCron sets the "default_cron" field.
func (u *TaskTypeUpsert) SetDefaultCron(v string) *TaskTypeUpsert {
	u.Set(tasktype.FieldDefaultCron, v)
	return u
}

// UpdateDefaultCron sets the "default_cron" field to the value that was provided on create.
func (u *TaskTypeUpsert) UpdateDefaultCron() *TaskTypeUpsert {
	u.SetExcluded(tasktype.FieldDefaultCron)
	return u
}

// ClearDefaultCron clears the value of the "default_cron" field.
func (u *TaskTypeUpsert) ClearDefaultCron() *TaskTypeUpsert {
	u.SetNull(tasktype.FieldDefaultCron)
	return u
}

// SetDefaultMaxRetry sets the "default_max_retry" field.
func (u *TaskTypeUpsert) SetDefaultMaxRetry(v int32) *TaskTypeUpsert {
	u.Set(tasktype.FieldDefaultMaxRetry, v)
	return u
}

// UpdateDefaultMaxRetry sets the "default_max_retry" field to the value that was provided on create.
func (u *TaskTypeUpsert) UpdateDefaultMaxRetry() *TaskTypeUpsert {
	u.SetExcluded(tasktype.FieldDefaultMaxRetry)
	return u
}

// AddDefaultMaxRetry adds v to the "default_max_retry" field.
func (u *TaskTypeUpsert) AddDefaultMaxRetry(v int32) *TaskTypeUpsert {
	u.Add(tasktype.FieldDefaultMaxRetry, v)
	return u
}

// SetRegisteredAt sets the "registered_at" field.
func (u *TaskTypeUpsert) SetRegisteredAt(v time.Time) *TaskTypeUpsert {
	u.Set(tasktype.FieldRegisteredAt, v)
	return u
}

// UpdateRegisteredAt sets the "registered_at" field to the value that was provided on create.
func (u *TaskTypeUpsert) UpdateRegisteredAt() *TaskTypeUpsert {
	u.SetExcluded(tasktype.FieldRegisteredAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TaskType.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TaskTypeUpsertOne) UpdateNewValues() *TaskTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskType.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TaskTypeUpsertOne) Ignore() *TaskTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskTypeUpsertOne) DoNothing() *TaskTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskTypeCreate.OnConflict
// documentation for more info.
func (u *TaskTypeUpsertOne) Update(set func(*TaskTypeUpsert)) *TaskTypeUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskTypeUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskType sets the "task_type" field.
func (u *TaskTypeUpsertOne) SetTaskType(v string) *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetTaskType(v)
	})
}

// UpdateTaskType sets the "task_type" field to the value that was provided on create.
func (u *TaskTypeUpsertOne) UpdateTaskType() *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateTaskType()
	})
}

// SetModuleID sets the "module_id" field.
func (u *TaskTypeUpsertOne) SetModuleID(v string) *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetModuleID(v)
	})
}

// UpdateModuleID sets the "module_id" field to the value that was provided on create.
func (u *TaskTypeUpsertOne) UpdateModuleID() *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateModuleID()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *TaskTypeUpsertOne) SetDisplayName(v string) *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *TaskTypeUpsertOne) UpdateDisplayName() *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateDisplayName()
	})
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *TaskTypeUpsertOne) ClearDisplayName() *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.ClearDisplayName()
	})
}

// SetDescription sets the "description" field.
func (u *TaskTypeUpsertOne) SetDescription(v string) *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TaskTypeUpsertOne) UpdateDescription() *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TaskTypeUpsertOne) ClearDescription() *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.ClearDescription()
	})
}

// SetPayloadSchema sets the "payload_schema" field.
func (u *TaskTypeUpsertOne) SetPayloadSchema(v string) *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetPayloadSchema(v)
	})
}

// UpdatePayloadSchema sets the "payload_schema" field to the value that was provided on create.
func (u *TaskTypeUpsertOne) UpdatePayloadSchema() *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdatePayloadSchema()
	})
}

// ClearPayloadSchema clears the value of the "payload_schema" field.
func (u *TaskTypeUpsertOne) ClearPayloadSchema() *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.ClearPayloadSchema()
	})
}

// SetDefaultCron sets the "default_cron" field.
func (u *TaskTypeUpsertOne) SetDefaultCron(v string) *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetDefaultCron(v)
	})
}

// UpdateDefaultCron sets the "default_cron" field to the value that was provided on create.
func (u *TaskTypeUpsertOne) UpdateDefaultCron() *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateDefaultCron()
	})
}

// ClearDefaultCron clears the value of the "default_cron" field.
func (u *TaskTypeUpsertOne) ClearDefaultCron() *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.ClearDefaultCron()
	})
}

// SetDefaultMaxRetry sets the "default_max_retry" field.
func (u *TaskTypeUpsertOne) SetDefaultMaxRetry(v int32) *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetDefaultMaxRetry(v)
	})
}

// AddDefaultMaxRetry adds v to the "default_max_retry" field.
func (u *TaskTypeUpsertOne) AddDefaultMaxRetry(v int32) *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.AddDefaultMaxRetry(v)
	})
}

// UpdateDefaultMaxRetry sets the "default_max_retry" field to the value that was provided on create.
func (u *TaskTypeUpsertOne) UpdateDefaultMaxRetry() *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateDefaultMaxRetry()
	})
}

// SetRegisteredAt sets the "registered_at" field.
func (u *TaskTypeUpsertOne) SetRegisteredAt(v time.Time) *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetRegisteredAt(v)
	})
}

// UpdateRegisteredAt sets the "registered_at" field to the value that was provided on create.
func (u *TaskTypeUpsertOne) UpdateRegisteredAt() *TaskTypeUpsertOne {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateRegisteredAt()
	})
}

// Exec executes the query.
func (u *TaskTypeUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskTypeCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskTypeUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TaskTypeUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TaskTypeUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TaskTypeCreateBulk is the builder for creating many TaskType entities in bulk.
type TaskTypeCreateBulk struct {
	config
	err      error
	builders []*TaskTypeCreate
	conflict []sql.ConflictOption
}

// Save creates the TaskType entities in the database.
func (_c *TaskTypeCreateBulk) Save(ctx context.Context) ([]*TaskType, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskType, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskTypeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskTypeCreateBulk) SaveX(ctx context.Context) []*TaskType {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskTypeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskTypeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskType.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskTypeUpsert) {
//			SetTaskType(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskTypeCreateBulk) OnConflict(opts ...sql.ConflictOption) *TaskTypeUpsertBulk {
	_c.conflict = opts
	return &TaskTypeUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskType.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskTypeCreateBulk) OnConflictColumns(columns ...string) *TaskTypeUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskTypeUpsertBulk{
		create: _c,
	}
}

// TaskTypeUpsertBulk is the builder for "upsert"-ing
// a bulk of TaskType nodes.
type TaskTypeUpsertBulk struct {
	create *TaskTypeCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TaskType.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TaskTypeUpsertBulk) UpdateNewValues() *TaskTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskType.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TaskTypeUpsertBulk) Ignore() *TaskTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskTypeUpsertBulk) DoNothing() *TaskTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskTypeCreateBulk.OnConflict
// documentation for more info.
func (u *TaskTypeUpsertBulk) Update(set func(*TaskTypeUpsert)) *TaskTypeUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskTypeUpsert{UpdateSet: update})
	}))
	return u
}

// SetTaskType sets the "task_type" field.
func (u *TaskTypeUpsertBulk) SetTaskType(v string) *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetTaskType(v)
	})
}

// UpdateTaskType sets the "task_type" field to the value that was provided on create.
func (u *TaskTypeUpsertBulk) UpdateTaskType() *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateTaskType()
	})
}

// SetModuleID sets the "module_id" field.
func (u *TaskTypeUpsertBulk) SetModuleID(v string) *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetModuleID(v)
	})
}

// UpdateModuleID sets the "module_id" field to the value that was provided on create.
func (u *TaskTypeUpsertBulk) UpdateModuleID() *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateModuleID()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *TaskTypeUpsertBulk) SetDisplayName(v string) *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *TaskTypeUpsertBulk) UpdateDisplayName() *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateDisplayName()
	})
}

// ClearDisplayName clears the value of the "display_name" field.
func (u *TaskTypeUpsertBulk) ClearDisplayName() *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.ClearDisplayName()
	})
}

// SetDescription sets the "description" field.
func (u *TaskTypeUpsertBulk) SetDescription(v string) *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *TaskTypeUpsertBulk) UpdateDescription() *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *TaskTypeUpsertBulk) ClearDescription() *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.ClearDescription()
	})
}

// SetPayloadSchema sets the "payload_schema" field.
func (u *TaskTypeUpsertBulk) SetPayloadSchema(v string) *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetPayloadSchema(v)
	})
}

// UpdatePayloadSchema sets the "payload_schema" field to the value that was provided on create.
func (u *TaskTypeUpsertBulk) UpdatePayloadSchema() *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdatePayloadSchema()
	})
}

// ClearPayloadSchema clears the value of the "payload_schema" field.
func (u *TaskTypeUpsertBulk) ClearPayloadSchema() *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.ClearPayloadSchema()
	})
}

// SetDefaultCron sets the "default_cron" field.
func (u *TaskTypeUpsertBulk) SetDefaultCron(v string) *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetDefaultCron(v)
	})
}

// UpdateDefaultCron sets the "default_cron" field to the value that was provided on create.
func (u *TaskTypeUpsertBulk) UpdateDefaultCron() *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateDefaultCron()
	})
}

// ClearDefaultCron clears the value of the "default_cron" field.
func (u *TaskTypeUpsertBulk) ClearDefaultCron() *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.ClearDefaultCron()
	})
}

// SetDefaultMaxRetry sets the "default_max_retry" field.
func (u *TaskTypeUpsertBulk) SetDefaultMaxRetry(v int32) *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetDefaultMaxRetry(v)
	})
}

// AddDefaultMaxRetry adds v to the "default_max_retry" field.
func (u *TaskTypeUpsertBulk) AddDefaultMaxRetry(v int32) *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.AddDefaultMaxRetry(v)
	})
}

// UpdateDefaultMaxRetry sets the "default_max_retry" field to the value that was provided on create.
func (u *TaskTypeUpsertBulk) UpdateDefaultMaxRetry() *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateDefaultMaxRetry()
	})
}

// SetRegisteredAt sets the "registered_at" field.
func (u *TaskTypeUpsertBulk) SetRegisteredAt(v time.Time) *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.SetRegisteredAt(v)
	})
}

// UpdateRegisteredAt sets the "registered_at" field to the value that was provided on create.
func (u *TaskTypeUpsertBulk) UpdateRegisteredAt() *TaskTypeUpsertBulk {
	return u.Update(func(s *TaskTypeUpsert) {
		s.UpdateRegisteredAt()
	})
}

// Exec executes the query.
func (u *TaskTypeUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TaskTypeCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskTypeCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskTypeUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
