// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/taskexecution"
)

// TaskExecutionDelete is the builder for deleting a TaskExecution entity.
type TaskExecutionDelete struct {
	config
	hooks    []Hook
	mutation *TaskExecutionMutation
}

// Where appends a list predicates to the TaskExecutionDelete builder.
func (_d *TaskExecutionDelete) Where(ps ...predicate.TaskExecution) *TaskExecutionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TaskExecutionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TaskExecutionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TaskExecutionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(taskexecution.Table, sqlgraph.NewFieldSpec(taskexecution.FieldID, field.TypeUint32))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TaskExecutionDeleteOne is the builder for deleting a single TaskExecution entity.
type TaskExecutionDeleteOne struct {
	_d *TaskExecutionDelete
}

// Where appends a list predicates to the TaskExecutionDelete builder.
func (_d *TaskExecutionDeleteOne) Where(ps ...predicate.TaskExecution) *TaskExecutionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TaskExecutionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{taskexecution.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TaskExecutionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
