// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/tasktype"
)

// TaskTypeUpdate is the builder for updating TaskType entities.
type TaskTypeUpdate struct {
	config
	hooks     []Hook
	mutation  *TaskTypeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TaskTypeUpdate builder.
func (_u *TaskTypeUpdate) Where(ps ...predicate.TaskType) *TaskTypeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTaskType sets the "task_type" field.
func (_u *TaskTypeUpdate) SetTaskType(v string) *TaskTypeUpdate {
	_u.mutation.SetTaskType(v)
	return _u
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (_u *TaskTypeUpdate) SetNillableTaskType(v *string) *TaskTypeUpdate {
	if v != nil {
		_u.SetTaskType(*v)
	}
	return _u
}

// SetModuleID sets the "module_id" field.
func (_u *TaskTypeUpdate) SetModuleID(v string) *TaskTypeUpdate {
	_u.mutation.SetModuleID(v)
	return _u
}

// SetNillableModuleID sets the "module_id" field if the given value is not nil.
func (_u *TaskTypeUpdate) SetNillableModuleID(v *string) *TaskTypeUpdate {
	if v != nil {
		_u.SetModuleID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *TaskTypeUpdate) SetDisplayName(v string) *TaskTypeUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *TaskTypeUpdate) SetNillableDisplayName(v *string) *TaskTypeUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *TaskTypeUpdate) ClearDisplayName() *TaskTypeUpdate {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskTypeUpdate) SetDescription(v string) *TaskTypeUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskTypeUpdate) SetNillableDescription(v *string) *TaskTypeUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskTypeUpdate) ClearDescription() *TaskTypeUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPayloadSchema sets the "payload_schema" field.
func (_u *TaskTypeUpdate) SetPayloadSchema(v string) *TaskTypeUpdate {
	_u.mutation.SetPayloadSchema(v)
	return _u
}

// SetNillablePayloadSchema sets the "payload_schema" field if the given value is not nil.
func (_u *TaskTypeUpdate) SetNillablePayloadSchema(v *string) *TaskTypeUpdate {
	if v != nil {
		_u.SetPayloadSchema(*v)
	}
	return _u
}

// ClearPayloadSchema clears the value of the "payload_schema" field.
func (_u *TaskTypeUpdate) ClearPayloadSchema() *TaskTypeUpdate {
	_u.mutation.ClearPayloadSchema()
	return _u
}

// SetDefaultCron sets the "default_cron" field.
func (_u *TaskTypeUpdate) SetDefaultCron(v string) *TaskTypeUpdate {
	_u.mutation.SetDefaultCron(v)
	return _u
}

// SetNillableDefaultCron sets the "default_cron" field if the given value is not nil.
func (_u *TaskTypeUpdate) SetNillableDefaultCron(v *string) *TaskTypeUpdate {
	if v != nil {
		_u.SetDefaultCron(*v)
	}
	return _u
}

// ClearDefaultCron clears the value of the "default_cron" field.
func (_u *TaskTypeUpdate) ClearDefaultCron() *TaskTypeUpdate {
	_u.mutation.ClearDefaultCron()
	return _u
}

// SetDefaultMaxRetry sets the "default_max_retry" field.
func (_u *TaskTypeUpdate) SetDefaultMaxRetry(v int32) *TaskTypeUpdate {
	_u.mutation.ResetDefaultMaxRetry()
	_u.mutation.SetDefaultMaxRetry(v)
	return _u
}

// SetNillableDefaultMaxRetry sets the "default_max_retry" field if the given value is not nil.
func (_u *TaskTypeUpdate) SetNillableDefaultMaxRetry(v *int32) *TaskTypeUpdate {
	if v != nil {
		_u.SetDefaultMaxRetry(*v)
	}
	return _u
}

// AddDefaultMaxRetry adds value to the "default_max_retry" field.
func (_u *TaskTypeUpdate) AddDefaultMaxRetry(v int32) *TaskTypeUpdate {
	_u.mutation.AddDefaultMaxRetry(v)
	return _u
}

// SetRegisteredAt sets the "registered_at" field.
func (_u *TaskTypeUpdate) SetRegisteredAt(v time.Time) *TaskTypeUpdate {
	_u.mutation.SetRegisteredAt(v)
	return _u
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (_u *TaskTypeUpdate) SetNillableRegisteredAt(v *time.Time) *TaskTypeUpdate {
	if v != nil {
		_u.SetRegisteredAt(*v)
	}
	return _u
}

// Mutation returns the TaskTypeMutation object of the builder.
func (_u *TaskTypeUpdate) Mutation() *TaskTypeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskTypeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskTypeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskTypeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskTypeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskTypeUpdate) check() error {
	if v, ok := _u.mutation.TaskType(); ok {
		if err := tasktype.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "TaskType.task_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModuleID(); ok {
		if err := tasktype.ModuleIDValidator(v); err != nil {
			return &ValidationError{Name: "module_id", err: fmt.Errorf(`ent: validator failed for field "TaskType.module_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TaskTypeUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TaskTypeUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TaskTypeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tasktype.Table, tasktype.Columns, sqlgraph.NewFieldSpec(tasktype.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskType(); ok {
		_spec.SetField(tasktype.FieldTaskType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModuleID(); ok {
		_spec.SetField(tasktype.FieldModuleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(tasktype.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(tasktype.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tasktype.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tasktype.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadSchema(); ok {
		_spec.SetField(tasktype.FieldPayloadSchema, field.TypeString, value)
	}
	if _u.mutation.PayloadSchemaCleared() {
		_spec.ClearField(tasktype.FieldPayloadSchema, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultCron(); ok {
		_spec.SetField(tasktype.FieldDefaultCron, field.TypeString, value)
	}
	if _u.mutation.DefaultCronCleared() {
		_spec.ClearField(tasktype.FieldDefaultCron, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultMaxRetry(); ok {
		_spec.SetField(tasktype.FieldDefaultMaxRetry, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedDefaultMaxRetry(); ok {
		_spec.AddField(tasktype.FieldDefaultMaxRetry, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.RegisteredAt(); ok {
		_spec.SetField(tasktype.FieldRegisteredAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tasktype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskTypeUpdateOne is the builder for updating a single TaskType entity.
type TaskTypeUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TaskTypeMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetTaskType sets the "task_type" field.
func (_u *TaskTypeUpdateOne) SetTaskType(v string) *TaskTypeUpdateOne {
	_u.mutation.SetTaskType(v)
	return _u
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (_u *TaskTypeUpdateOne) SetNillableTaskType(v *string) *TaskTypeUpdateOne {
	if v != nil {
		_u.SetTaskType(*v)
	}
	return _u
}

// SetModuleID sets the "module_id" field.
func (_u *TaskTypeUpdateOne) SetModuleID(v string) *TaskTypeUpdateOne {
	_u.mutation.SetModuleID(v)
	return _u
}

// SetNillableModuleID sets the "module_id" field if the given value is not nil.
func (_u *TaskTypeUpdateOne) SetNillableModuleID(v *string) *TaskTypeUpdateOne {
	if v != nil {
		_u.SetModuleID(*v)
	}
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *TaskTypeUpdateOne) SetDisplayName(v string) *TaskTypeUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *TaskTypeUpdateOne) SetNillableDisplayName(v *string) *TaskTypeUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// ClearDisplayName clears the value of the "display_name" field.
func (_u *TaskTypeUpdateOne) ClearDisplayName() *TaskTypeUpdateOne {
	_u.mutation.ClearDisplayName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *TaskTypeUpdateOne) SetDescription(v string) *TaskTypeUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *TaskTypeUpdateOne) SetNillableDescription(v *string) *TaskTypeUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *TaskTypeUpdateOne) ClearDescription() *TaskTypeUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPayloadSchema sets the "payload_schema" field.
func (_u *TaskTypeUpdateOne) SetPayloadSchema(v string) *TaskTypeUpdateOne {
	_u.mutation.SetPayloadSchema(v)
	return _u
}

// SetNillablePayloadSchema sets the "payload_schema" field if the given value is not nil.
func (_u *TaskTypeUpdateOne) SetNillablePayloadSchema(v *string) *TaskTypeUpdateOne {
	if v != nil {
		_u.SetPayloadSchema(*v)
	}
	return _u
}

// ClearPayloadSchema clears the value of the "payload_schema" field.
func (_u *TaskTypeUpdateOne) ClearPayloadSchema() *TaskTypeUpdateOne {
	_u.mutation.ClearPayloadSchema()
	return _u
}

// SetDefaultCron sets the "default_cron" field.
func (_u *TaskTypeUpdateOne) SetDefaultCron(v string) *TaskTypeUpdateOne {
	_u.mutation.SetDefaultCron(v)
	return _u
}

// SetNillableDefaultCron sets the "default_cron" field if the given value is not nil.
func (_u *TaskTypeUpdateOne) SetNillableDefaultCron(v *string) *TaskTypeUpdateOne {
	if v != nil {
		_u.SetDefaultCron(*v)
	}
	return _u
}

// ClearDefaultCron clears the value of the "default_cron" field.
func (_u *TaskTypeUpdateOne) ClearDefaultCron() *TaskTypeUpdateOne {
	_u.mutation.ClearDefaultCron()
	return _u
}

// SetDefaultMaxRetry sets the "default_max_retry" field.
func (_u *TaskTypeUpdateOne) SetDefaultMaxRetry(v int32) *TaskTypeUpdateOne {
	_u.mutation.ResetDefaultMaxRetry()
	_u.mutation.SetDefaultMaxRetry(v)
	return _u
}

// SetNillableDefaultMaxRetry sets the "default_max_retry" field if the given value is not nil.
func (_u *TaskTypeUpdateOne) SetNillableDefaultMaxRetry(v *int32) *TaskTypeUpdateOne {
	if v != nil {
		_u.SetDefaultMaxRetry(*v)
	}
	return _u
}

// AddDefaultMaxRetry adds value to the "default_max_retry" field.
func (_u *TaskTypeUpdateOne) AddDefaultMaxRetry(v int32) *TaskTypeUpdateOne {
	_u.mutation.AddDefaultMaxRetry(v)
	return _u
}

// SetRegisteredAt sets the "registered_at" field.
func (_u *TaskTypeUpdateOne) SetRegisteredAt(v time.Time) *TaskTypeUpdateOne {
	_u.mutation.SetRegisteredAt(v)
	return _u
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (_u *TaskTypeUpdateOne) SetNillableRegisteredAt(v *time.Time) *TaskTypeUpdateOne {
	if v != nil {
		_u.SetRegisteredAt(*v)
	}
	return _u
}

// Mutation returns the TaskTypeMutation object of the builder.
func (_u *TaskTypeUpdateOne) Mutation() *TaskTypeMutation {
	return _u.mutation
}

// Where appends a list predicates to the TaskTypeUpdate builder.
func (_u *TaskTypeUpdateOne) Where(ps ...predicate.TaskType) *TaskTypeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskTypeUpdateOne) Select(field string, fields ...string) *TaskTypeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskType entity.
func (_u *TaskTypeUpdateOne) Save(ctx context.Context) (*TaskType, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskTypeUpdateOne) SaveX(ctx context.Context) *TaskType {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskTypeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskTypeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskTypeUpdateOne) check() error {
	if v, ok := _u.mutation.TaskType(); ok {
		if err := tasktype.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "TaskType.task_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModuleID(); ok {
		if err := tasktype.ModuleIDValidator(v); err != nil {
			return &ValidationError{Name: "module_id", err: fmt.Errorf(`ent: validator failed for field "TaskType.module_id": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TaskTypeUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TaskTypeUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TaskTypeUpdateOne) sqlSave(ctx context.Context) (_node *TaskType, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tasktype.Table, tasktype.Columns, sqlgraph.NewFieldSpec(tasktype.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskType.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tasktype.FieldID)
		for _, f := range fields {
			if !tasktype.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tasktype.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TaskType(); ok {
		_spec.SetField(tasktype.FieldTaskType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModuleID(); ok {
		_spec.SetField(tasktype.FieldModuleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(tasktype.FieldDisplayName, field.TypeString, value)
	}
	if _u.mutation.DisplayNameCleared() {
		_spec.ClearField(tasktype.FieldDisplayName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(tasktype.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(tasktype.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.PayloadSchema(); ok {
		_spec.SetField(tasktype.FieldPayloadSchema, field.TypeString, value)
	}
	if _u.mutation.PayloadSchemaCleared() {
		_spec.ClearField(tasktype.FieldPayloadSchema, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultCron(); ok {
		_spec.SetField(tasktype.FieldDefaultCron, field.TypeString, value)
	}
	if _u.mutation.DefaultCronCleared() {
		_spec.ClearField(tasktype.FieldDefaultCron, field.TypeString)
	}
	if value, ok := _u.mutation.DefaultMaxRetry(); ok {
		_spec.SetField(tasktype.FieldDefaultMaxRetry, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedDefaultMaxRetry(); ok {
		_spec.AddField(tasktype.FieldDefaultMaxRetry, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.RegisteredAt(); ok {
		_spec.SetField(tasktype.FieldRegisteredAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TaskType{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tasktype.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
