// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/taskexecution"
)

// TaskExecutionCreate is the builder for creating a TaskExecution entity.
type TaskExecutionCreate struct {
	config
	mutation *TaskExecutionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetExecutionID sets the "execution_id" field.
func (_c *TaskExecutionCreate) SetExecutionID(v string) *TaskExecutionCreate {
	_c.mutation.SetExecutionID(v)
	return _c
}

// SetTaskType sets the "task_type" field.
func (_c *TaskExecutionCreate) SetTaskType(v string) *TaskExecutionCreate {
	_c.mutation.SetTaskType(v)
	return _c
}

// SetModuleID sets the "module_id" field.
func (_c *TaskExecutionCreate) SetModuleID(v string) *TaskExecutionCreate {
	_c.mutation.SetModuleID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *TaskExecutionCreate) SetStatus(v string) *TaskExecutionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *TaskExecutionCreate) SetMessage(v string) *TaskExecutionCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *TaskExecutionCreate) SetNillableMessage(v *string) *TaskExecutionCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetAttempt sets the "attempt" field.
func (_c *TaskExecutionCreate) SetAttempt(v int32) *TaskExecutionCreate {
	_c.mutation.SetAttempt(v)
	return _c
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_c *TaskExecutionCreate) SetNillableAttempt(v *int32) *TaskExecutionCreate {
	if v != nil {
		_c.SetAttempt(*v)
	}
	return _c
}

// SetDurationMs sets the "duration_ms" field.
func (_c *TaskExecutionCreate) SetDurationMs(v int64) *TaskExecutionCreate {
	_c.mutation.SetDurationMs(v)
	return _c
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_c *TaskExecutionCreate) SetNillableDurationMs(v *int64) *TaskExecutionCreate {
	if v != nil {
		_c.SetDurationMs(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *TaskExecutionCreate) SetStartedAt(v time.Time) *TaskExecutionCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *TaskExecutionCreate) SetNillableStartedAt(v *time.Time) *TaskExecutionCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *TaskExecutionCreate) SetFinishedAt(v time.Time) *TaskExecutionCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *TaskExecutionCreate) SetNillableFinishedAt(v *time.Time) *TaskExecutionCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetTenantID sets the "tenant_id" field.
func (_c *TaskExecutionCreate) SetTenantID(v uint32) *TaskExecutionCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_c *TaskExecutionCreate) SetNillableTenantID(v *uint32) *TaskExecutionCreate {
	if v != nil {
		_c.SetTenantID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *TaskExecutionCreate) SetID(v uint32) *TaskExecutionCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the TaskExecutionMutation object of the builder.
func (_c *TaskExecutionCreate) Mutation() *TaskExecutionMutation {
	return _c.mutation
}

// Save creates the TaskExecution in the database.
func (_c *TaskExecutionCreate) Save(ctx context.Context) (*TaskExecution, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TaskExecutionCreate) SaveX(ctx context.Context) *TaskExecution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskExecutionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskExecutionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *TaskExecutionCreate) defaults() {
	if _, ok := _c.mutation.Attempt(); !ok {
		v := taskexecution.DefaultAttempt
		_c.mutation.SetAttempt(v)
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		v := taskexecution.DefaultDurationMs
		_c.mutation.SetDurationMs(v)
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := taskexecution.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		v := taskexecution.DefaultTenantID
		_c.mutation.SetTenantID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TaskExecutionCreate) check() error {
	if _, ok := _c.mutation.ExecutionID(); !ok {
		return &ValidationError{Name: "execution_id", err: errors.New(`ent: missing required field "TaskExecution.execution_id"`)}
	}
	if v, ok := _c.mutation.ExecutionID(); ok {
		if err := taskexecution.ExecutionIDValidator(v); err != nil {
			return &ValidationError{Name: "execution_id", err: fmt.Errorf(`ent: validator failed for field "TaskExecution.execution_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TaskType(); !ok {
		return &ValidationError{Name: "task_type", err: errors.New(`ent: missing required field "TaskExecution.task_type"`)}
	}
	if v, ok := _c.mutation.TaskType(); ok {
		if err := taskexecution.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "TaskExecution.task_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ModuleID(); !ok {
		return &ValidationError{Name: "module_id", err: errors.New(`ent: missing required field "TaskExecution.module_id"`)}
	}
	if v, ok := _c.mutation.ModuleID(); ok {
		if err := taskexecution.ModuleIDValidator(v); err != nil {
			return &ValidationError{Name: "module_id", err: fmt.Errorf(`ent: validator failed for field "TaskExecution.module_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "TaskExecution.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := taskexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TaskExecution.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempt(); !ok {
		return &ValidationError{Name: "attempt", err: errors.New(`ent: missing required field "TaskExecution.attempt"`)}
	}
	if _, ok := _c.mutation.DurationMs(); !ok {
		return &ValidationError{Name: "duration_ms", err: errors.New(`ent: missing required field "TaskExecution.duration_ms"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "TaskExecution.started_at"`)}
	}
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TaskExecution.tenant_id"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := taskexecution.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "TaskExecution.id": %w`, err)}
		}
	}
	return nil
}

func (_c *TaskExecutionCreate) sqlSave(ctx context.Context) (*TaskExecution, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint32(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TaskExecutionCreate) createSpec() (*TaskExecution, *sqlgraph.CreateSpec) {
	var (
		_node = &TaskExecution{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(taskexecution.Table, sqlgraph.NewFieldSpec(taskexecution.FieldID, field.TypeUint32))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.ExecutionID(); ok {
		_spec.SetField(taskexecution.FieldExecutionID, field.TypeString, value)
		_node.ExecutionID = value
	}
	if value, ok := _c.mutation.TaskType(); ok {
		_spec.SetField(taskexecution.FieldTaskType, field.TypeString, value)
		_node.TaskType = value
	}
	if value, ok := _c.mutation.ModuleID(); ok {
		_spec.SetField(taskexecution.FieldModuleID, field.TypeString, value)
		_node.ModuleID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(taskexecution.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(taskexecution.FieldMessage, field.TypeString, value)
		_node.Message = &value
	}
	if value, ok := _c.mutation.Attempt(); ok {
		_spec.SetField(taskexecution.FieldAttempt, field.TypeInt32, value)
		_node.Attempt = value
	}
	if value, ok := _c.mutation.DurationMs(); ok {
		_spec.SetField(taskexecution.FieldDurationMs, field.TypeInt64, value)
		_node.DurationMs = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(taskexecution.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(taskexecution.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(taskexecution.FieldTenantID, field.TypeUint32, value)
		_node.TenantID = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskExecution.Create().
//		SetExecutionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskExecutionUpsert) {
//			SetExecutionID(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskExecutionCreate) OnConflict(opts ...sql.ConflictOption) *TaskExecutionUpsertOne {
	_c.conflict = opts
	return &TaskExecutionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskExecution.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskExecutionCreate) OnConflictColumns(columns ...string) *TaskExecutionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskExecutionUpsertOne{
		create: _c,
	}
}

type (
	// TaskExecutionUpsertOne is the builder for "upsert"-ing
	//  one TaskExecution node.
	TaskExecutionUpsertOne struct {
		create *TaskExecutionCreate
	}

	// TaskExecutionUpsert is the "OnConflict" setter.
	TaskExecutionUpsert struct {
		*sql.UpdateSet
	}
)

// SetExecutionID sets the "execution_id" field.
func (u *TaskExecutionUpsert) SetExecutionID(v string) *TaskExecutionUpsert {
	u.Set(taskexecution.FieldExecutionID, v)
	return u
}

// UpdateExecutionID sets the "execution_id" field to the value that was provided on create.
func (u *TaskExecutionUpsert) UpdateExecutionID() *TaskExecutionUpsert {
	u.SetExcluded(taskexecution.FieldExecutionID)
	return u
}

// SetTaskType sets the "task_type" field.
func (u *TaskExecutionUpsert) SetTaskType(v string) *TaskExecutionUpsert {
	u.Set(taskexecution.FieldTaskType, v)
	return u
}

// UpdateTaskType sets the "task_type" field to the value that was provided on create.
func (u *TaskExecutionUpsert) UpdateTaskType() *TaskExecutionUpsert {
	u.SetExcluded(taskexecution.FieldTaskType)
	return u
}

// SetModuleID sets the "module_id" field.
func (u *TaskExecutionUpsert) SetModuleID(v string) *TaskExecutionUpsert {
	u.Set(taskexecution.FieldModuleID, v)
	return u
}

// UpdateModuleID sets the "module_id" field to the value that was provided on create.
func (u *TaskExecutionUpsert) UpdateModuleID() *TaskExecutionUpsert {
	u.SetExcluded(taskexecution.FieldModuleID)
	return u
}

// SetStatus sets the "status" field.
func (u *TaskExecutionUpsert) SetStatus(v string) *TaskExecutionUpsert {
	u.Set(taskexecution.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TaskExecutionUpsert) UpdateStatus() *TaskExecutionUpsert {
	u.SetExcluded(taskexecution.FieldStatus)
	return u
}

// SetMessage sets the "message" field.
func (u *TaskExecutionUpsert) SetMessage(v string) *TaskExecutionUpsert {
	u.Set(taskexecution.FieldMessage, v)
	return u
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *TaskExecutionUpsert) UpdateMessage() *TaskExecutionUpsert {
	u.SetExcluded(taskexecution.FieldMessage)
	return u
}

// ClearMessage clears the value of the "message" field.
func (u *TaskExecutionUpsert) ClearMessage() *TaskExecutionUpsert {
	u.SetNull(taskexecution.FieldMessage)
	return u
}

// SetAttempt sets the "attempt" field.
func (u *TaskExecutionUpsert) SetAttempt(v int32) *TaskExecutionUpsert {
	u.Set(taskexecution.FieldAttempt, v)
	return u
}

// UpdateAttempt sets the "attempt" field to the value that was provided on create.
func (u *TaskExecutionUpsert) UpdateAttempt() *TaskExecutionUpsert {
	u.SetExcluded(taskexecution.FieldAttempt)
	return u
}

// AddAttempt adds v to the "attempt" field.
func (u *TaskExecutionUpsert) AddAttempt(v int32) *TaskExecutionUpsert {
	u.Add(taskexecution.FieldAttempt, v)
	return u
}

// SetDurationMs sets the "duration_ms" field.
func (u *TaskExecutionUpsert) SetDurationMs(v int64) *TaskExecutionUpsert {
	u.Set(taskexecution.FieldDurationMs, v)
	return u
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *TaskExecutionUpsert) UpdateDurationMs() *TaskExecutionUpsert {
	u.SetExcluded(taskexecution.FieldDurationMs)
	return u
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *TaskExecutionUpsert) AddDurationMs(v int64) *TaskExecutionUpsert {
	u.Add(taskexecution.FieldDurationMs, v)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *TaskExecutionUpsert) SetStartedAt(v time.Time) *TaskExecutionUpsert {
	u.Set(taskexecution.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *TaskExecutionUpsert) UpdateStartedAt() *TaskExecutionUpsert {
	u.SetExcluded(taskexecution.FieldStartedAt)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *TaskExecutionUpsert) SetFinishedAt(v time.Time) *TaskExecutionUpsert {
	u.Set(taskexecution.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *TaskExecutionUpsert) UpdateFinishedAt() *TaskExecutionUpsert {
	u.SetExcluded(taskexecution.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *TaskExecutionUpsert) ClearFinishedAt() *TaskExecutionUpsert {
	u.SetNull(taskexecution.FieldFinishedAt)
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *TaskExecutionUpsert) SetTenantID(v uint32) *TaskExecutionUpsert {
	u.Set(taskexecution.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TaskExecutionUpsert) UpdateTenantID() *TaskExecutionUpsert {
	u.SetExcluded(taskexecution.FieldTenantID)
	return u
}

// AddTenantID adds v to the "tenant_id" field.
func (u *TaskExecutionUpsert) AddTenantID(v uint32) *TaskExecutionUpsert {
	u.Add(taskexecution.FieldTenantID, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.TaskExecution.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskexecution.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskExecutionUpsertOne) UpdateNewValues() *TaskExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(taskexecution.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskExecution.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TaskExecutionUpsertOne) Ignore() *TaskExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskExecutionUpsertOne) DoNothing() *TaskExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskExecutionCreate.OnConflict
// documentation for more info.
func (u *TaskExecutionUpsertOne) Update(set func(*TaskExecutionUpsert)) *TaskExecutionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskExecutionUpsert{UpdateSet: update})
	}))
	return u
}

// SetExecutionID sets the "execution_id" field.
func (u *TaskExecutionUpsertOne) SetExecutionID(v string) *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetExecutionID(v)
	})
}

// UpdateExecutionID sets the "execution_id" field to the value that was provided on create.
func (u *TaskExecutionUpsertOne) UpdateExecutionID() *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateExecutionID()
	})
}

// SetTaskType sets the "task_type" field.
func (u *TaskExecutionUpsertOne) SetTaskType(v string) *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetTaskType(v)
	})
}

// UpdateTaskType sets the "task_type" field to the value that was provided on create.
func (u *TaskExecutionUpsertOne) UpdateTaskType() *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateTaskType()
	})
}

// SetModuleID sets the "module_id" field.
func (u *TaskExecutionUpsertOne) SetModuleID(v string) *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetModuleID(v)
	})
}

// UpdateModuleID sets the "module_id" field to the value that was provided on create.
func (u *TaskExecutionUpsertOne) UpdateModuleID() *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateModuleID()
	})
}

// SetStatus sets the "status" field.
func (u *TaskExecutionUpsertOne) SetStatus(v string) *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TaskExecutionUpsertOne) UpdateStatus() *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateStatus()
	})
}

// SetMessage sets the "message" field.
func (u *TaskExecutionUpsertOne) SetMessage(v string) *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *TaskExecutionUpsertOne) UpdateMessage() *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *TaskExecutionUpsertOne) ClearMessage() *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.ClearMessage()
	})
}

// SetAttempt sets the "attempt" field.
func (u *TaskExecutionUpsertOne) SetAttempt(v int32) *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetAttempt(v)
	})
}

// AddAttempt adds v to the "attempt" field.
func (u *TaskExecutionUpsertOne) AddAttempt(v int32) *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.AddAttempt(v)
	})
}

// UpdateAttempt sets the "attempt" field to the value that was provided on create.
func (u *TaskExecutionUpsertOne) UpdateAttempt() *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateAttempt()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *TaskExecutionUpsertOne) SetDurationMs(v int64) *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *TaskExecutionUpsertOne) AddDurationMs(v int64) *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *TaskExecutionUpsertOne) UpdateDurationMs() *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateDurationMs()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *TaskExecutionUpsertOne) SetStartedAt(v time.Time) *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *TaskExecutionUpsertOne) UpdateStartedAt() *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *TaskExecutionUpsertOne) SetFinishedAt(v time.Time) *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *TaskExecutionUpsertOne) UpdateFinishedAt() *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *TaskExecutionUpsertOne) ClearFinishedAt() *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.ClearFinishedAt()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *TaskExecutionUpsertOne) SetTenantID(v uint32) *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *TaskExecutionUpsertOne) AddTenantID(v uint32) *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TaskExecutionUpsertOne) UpdateTenantID() *TaskExecutionUpsertOne {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateTenantID()
	})
}

// Exec executes the query.
func (u *TaskExecutionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskExecutionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskExecutionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TaskExecutionUpsertOne) ID(ctx context.Context) (id uint32, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TaskExecutionUpsertOne) IDX(ctx context.Context) uint32 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TaskExecutionCreateBulk is the builder for creating many TaskExecution entities in bulk.
type TaskExecutionCreateBulk struct {
	config
	err      error
	builders []*TaskExecutionCreate
	conflict []sql.ConflictOption
}

// Save creates the TaskExecution entities in the database.
func (_c *TaskExecutionCreateBulk) Save(ctx context.Context) ([]*TaskExecution, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TaskExecution, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TaskExecutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint32(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TaskExecutionCreateBulk) SaveX(ctx context.Context) []*TaskExecution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TaskExecutionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TaskExecutionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TaskExecution.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TaskExecutionUpsert) {
//			SetExecutionID(v+v).
//		}).
//		Exec(ctx)
func (_c *TaskExecutionCreateBulk) OnConflict(opts ...sql.ConflictOption) *TaskExecutionUpsertBulk {
	_c.conflict = opts
	return &TaskExecutionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TaskExecution.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TaskExecutionCreateBulk) OnConflictColumns(columns ...string) *TaskExecutionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TaskExecutionUpsertBulk{
		create: _c,
	}
}

// TaskExecutionUpsertBulk is the builder for "upsert"-ing
// a bulk of TaskExecution nodes.
type TaskExecutionUpsertBulk struct {
	create *TaskExecutionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TaskExecution.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(taskexecution.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *TaskExecutionUpsertBulk) UpdateNewValues() *TaskExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(taskexecution.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TaskExecution.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TaskExecutionUpsertBulk) Ignore() *TaskExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TaskExecutionUpsertBulk) DoNothing() *TaskExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TaskExecutionCreateBulk.OnConflict
// documentation for more info.
func (u *TaskExecutionUpsertBulk) Update(set func(*TaskExecutionUpsert)) *TaskExecutionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TaskExecutionUpsert{UpdateSet: update})
	}))
	return u
}

// SetExecutionID sets the "execution_id" field.
func (u *TaskExecutionUpsertBulk) SetExecutionID(v string) *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetExecutionID(v)
	})
}

// UpdateExecutionID sets the "execution_id" field to the value that was provided on create.
func (u *TaskExecutionUpsertBulk) UpdateExecutionID() *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateExecutionID()
	})
}

// SetTaskType sets the "task_type" field.
func (u *TaskExecutionUpsertBulk) SetTaskType(v string) *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetTaskType(v)
	})
}

// UpdateTaskType sets the "task_type" field to the value that was provided on create.
func (u *TaskExecutionUpsertBulk) UpdateTaskType() *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateTaskType()
	})
}

// SetModuleID sets the "module_id" field.
func (u *TaskExecutionUpsertBulk) SetModuleID(v string) *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetModuleID(v)
	})
}

// UpdateModuleID sets the "module_id" field to the value that was provided on create.
func (u *TaskExecutionUpsertBulk) UpdateModuleID() *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateModuleID()
	})
}

// SetStatus sets the "status" field.
func (u *TaskExecutionUpsertBulk) SetStatus(v string) *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *TaskExecutionUpsertBulk) UpdateStatus() *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateStatus()
	})
}

// SetMessage sets the "message" field.
func (u *TaskExecutionUpsertBulk) SetMessage(v string) *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetMessage(v)
	})
}

// UpdateMessage sets the "message" field to the value that was provided on create.
func (u *TaskExecutionUpsertBulk) UpdateMessage() *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateMessage()
	})
}

// ClearMessage clears the value of the "message" field.
func (u *TaskExecutionUpsertBulk) ClearMessage() *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.ClearMessage()
	})
}

// SetAttempt sets the "attempt" field.
func (u *TaskExecutionUpsertBulk) SetAttempt(v int32) *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetAttempt(v)
	})
}

// AddAttempt adds v to the "attempt" field.
func (u *TaskExecutionUpsertBulk) AddAttempt(v int32) *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.AddAttempt(v)
	})
}

// UpdateAttempt sets the "attempt" field to the value that was provided on create.
func (u *TaskExecutionUpsertBulk) UpdateAttempt() *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateAttempt()
	})
}

// SetDurationMs sets the "duration_ms" field.
func (u *TaskExecutionUpsertBulk) SetDurationMs(v int64) *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetDurationMs(v)
	})
}

// AddDurationMs adds v to the "duration_ms" field.
func (u *TaskExecutionUpsertBulk) AddDurationMs(v int64) *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.AddDurationMs(v)
	})
}

// UpdateDurationMs sets the "duration_ms" field to the value that was provided on create.
func (u *TaskExecutionUpsertBulk) UpdateDurationMs() *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateDurationMs()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *TaskExecutionUpsertBulk) SetStartedAt(v time.Time) *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *TaskExecutionUpsertBulk) UpdateStartedAt() *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateStartedAt()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *TaskExecutionUpsertBulk) SetFinishedAt(v time.Time) *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *TaskExecutionUpsertBulk) UpdateFinishedAt() *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *TaskExecutionUpsertBulk) ClearFinishedAt() *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.ClearFinishedAt()
	})
}

// SetTenantID sets the "tenant_id" field.
func (u *TaskExecutionUpsertBulk) SetTenantID(v uint32) *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.SetTenantID(v)
	})
}

// AddTenantID adds v to the "tenant_id" field.
func (u *TaskExecutionUpsertBulk) AddTenantID(v uint32) *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.AddTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *TaskExecutionUpsertBulk) UpdateTenantID() *TaskExecutionUpsertBulk {
	return u.Update(func(s *TaskExecutionUpsert) {
		s.UpdateTenantID()
	})
}

// Exec executes the query.
func (u *TaskExecutionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TaskExecutionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TaskExecutionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TaskExecutionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
