// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	schedulerpb "github.com/go-tangra/go-tangra-scheduler/gen/go/scheduler/service/v1"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/task"
)

// Scheduled tasks
type Task struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 创建者ID
	CreatedBy *uint32 `json:"created_by,omitempty"`
	// 更新者ID
	UpdatedBy *uint32 `json:"updated_by,omitempty"`
	// 删除者ID
	DeletedBy *uint32 `json:"deleted_by,omitempty"`
	// 备注
	Remark *string `json:"remark,omitempty"`
	// 租户ID
	TenantID *uint32 `json:"tenant_id,omitempty"`
	// Task type
	Type *task.Type `json:"type,omitempty"`
	// Task execution type name (e.g., paperless:ocr-reindex)
	TypeName *string `json:"type_name,omitempty"`
	// Owning module ID (resolved from task type registry)
	ModuleID *string `json:"module_id,omitempty"`
	// Task data in JSON format
	TaskPayload *string `json:"task_payload,omitempty"`
	// Cron expression for periodic scheduling
	CronSpec *string `json:"cron_spec,omitempty"`
	// Task execution options
	TaskOptions *schedulerpb.TaskOption `json:"task_options,omitempty"`
	// Enable/disable task
	Enable *bool `json:"enable,omitempty"`
	// When the task last executed
	LastRunAt *time.Time `json:"last_run_at,omitempty"`
	// Last execution status: success, failed, running
	LastRunStatus *string `json:"last_run_status,omitempty"`
	// Last execution result or error message
	LastRunMessage *string `json:"last_run_message,omitempty"`
	// Total execution count
	RunCount     int32 `json:"run_count,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Task) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case task.FieldTaskOptions:
			values[i] = new([]byte)
		case task.FieldEnable:
			values[i] = new(sql.NullBool)
		case task.FieldID, task.FieldCreatedBy, task.FieldUpdatedBy, task.FieldDeletedBy, task.FieldTenantID, task.FieldRunCount:
			values[i] = new(sql.NullInt64)
		case task.FieldRemark, task.FieldType, task.FieldTypeName, task.FieldModuleID, task.FieldTaskPayload, task.FieldCronSpec, task.FieldLastRunStatus, task.FieldLastRunMessage:
			values[i] = new(sql.NullString)
		case task.FieldCreatedAt, task.FieldUpdatedAt, task.FieldDeletedAt, task.FieldLastRunAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Task fields.
func (_m *Task) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case task.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case task.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case task.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case task.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case task.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(uint32)
				*_m.CreatedBy = uint32(value.Int64)
			}
		case task.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(uint32)
				*_m.UpdatedBy = uint32(value.Int64)
			}
		case task.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = new(uint32)
				*_m.DeletedBy = uint32(value.Int64)
			}
		case task.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = new(string)
				*_m.Remark = value.String
			}
		case task.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = new(uint32)
				*_m.TenantID = uint32(value.Int64)
			}
		case task.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = new(task.Type)
				*_m.Type = task.Type(value.String)
			}
		case task.FieldTypeName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type_name", values[i])
			} else if value.Valid {
				_m.TypeName = new(string)
				*_m.TypeName = value.String
			}
		case task.FieldModuleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field module_id", values[i])
			} else if value.Valid {
				_m.ModuleID = new(string)
				*_m.ModuleID = value.String
			}
		case task.FieldTaskPayload:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_payload", values[i])
			} else if value.Valid {
				_m.TaskPayload = new(string)
				*_m.TaskPayload = value.String
			}
		case task.FieldCronSpec:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cron_spec", values[i])
			} else if value.Valid {
				_m.CronSpec = new(string)
				*_m.CronSpec = value.String
			}
		case task.FieldTaskOptions:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field task_options", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.TaskOptions); err != nil {
					return fmt.Errorf("unmarshal field task_options: %w", err)
				}
			}
		case task.FieldEnable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enable", values[i])
			} else if value.Valid {
				_m.Enable = new(bool)
				*_m.Enable = value.Bool
			}
		case task.FieldLastRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_run_at", values[i])
			} else if value.Valid {
				_m.LastRunAt = new(time.Time)
				*_m.LastRunAt = value.Time
			}
		case task.FieldLastRunStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_run_status", values[i])
			} else if value.Valid {
				_m.LastRunStatus = new(string)
				*_m.LastRunStatus = value.String
			}
		case task.FieldLastRunMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_run_message", values[i])
			} else if value.Valid {
				_m.LastRunMessage = new(string)
				*_m.LastRunMessage = value.String
			}
		case task.FieldRunCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field run_count", values[i])
			} else if value.Valid {
				_m.RunCount = int32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Task.
// This includes values selected through modifiers, order, etc.
func (_m *Task) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Task.
// Note that you need to call Task.Unwrap() before calling this method if this Task
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Task) Update() *TaskUpdateOne {
	return NewTaskClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Task entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Task) Unwrap() *Task {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Task is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Task) String() string {
	var builder strings.Builder
	builder.WriteString("Task(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DeletedBy; v != nil {
		builder.WriteString("deleted_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Remark; v != nil {
		builder.WriteString("remark=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TenantID; v != nil {
		builder.WriteString("tenant_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Type; v != nil {
		builder.WriteString("type=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TypeName; v != nil {
		builder.WriteString("type_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ModuleID; v != nil {
		builder.WriteString("module_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TaskPayload; v != nil {
		builder.WriteString("task_payload=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CronSpec; v != nil {
		builder.WriteString("cron_spec=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("task_options=")
	builder.WriteString(fmt.Sprintf("%v", _m.TaskOptions))
	builder.WriteString(", ")
	if v := _m.Enable; v != nil {
		builder.WriteString("enable=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastRunAt; v != nil {
		builder.WriteString("last_run_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastRunStatus; v != nil {
		builder.WriteString("last_run_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastRunMessage; v != nil {
		builder.WriteString("last_run_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("run_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RunCount))
	builder.WriteByte(')')
	return builder.String()
}

// Tasks is a parsable slice of Task.
type Tasks []*Task
