// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/predicate"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/taskexecution"
)

// TaskExecutionUpdate is the builder for updating TaskExecution entities.
type TaskExecutionUpdate struct {
	config
	hooks     []Hook
	mutation  *TaskExecutionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the TaskExecutionUpdate builder.
func (_u *TaskExecutionUpdate) Where(ps ...predicate.TaskExecution) *TaskExecutionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetExecutionID sets the "execution_id" field.
func (_u *TaskExecutionUpdate) SetExecutionID(v string) *TaskExecutionUpdate {
	_u.mutation.SetExecutionID(v)
	return _u
}

// SetNillableExecutionID sets the "execution_id" field if the given value is not nil.
func (_u *TaskExecutionUpdate) SetNillableExecutionID(v *string) *TaskExecutionUpdate {
	if v != nil {
		_u.SetExecutionID(*v)
	}
	return _u
}

// SetTaskType sets the "task_type" field.
func (_u *TaskExecutionUpdate) SetTaskType(v string) *TaskExecutionUpdate {
	_u.mutation.SetTaskType(v)
	return _u
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (_u *TaskExecutionUpdate) SetNillableTaskType(v *string) *TaskExecutionUpdate {
	if v != nil {
		_u.SetTaskType(*v)
	}
	return _u
}

// SetModuleID sets the "module_id" field.
func (_u *TaskExecutionUpdate) SetModuleID(v string) *TaskExecutionUpdate {
	_u.mutation.SetModuleID(v)
	return _u
}

// SetNillableModuleID sets the "module_id" field if the given value is not nil.
func (_u *TaskExecutionUpdate) SetNillableModuleID(v *string) *TaskExecutionUpdate {
	if v != nil {
		_u.SetModuleID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskExecutionUpdate) SetStatus(v string) *TaskExecutionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskExecutionUpdate) SetNillableStatus(v *string) *TaskExecutionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *TaskExecutionUpdate) SetMessage(v string) *TaskExecutionUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *TaskExecutionUpdate) SetNillableMessage(v *string) *TaskExecutionUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *TaskExecutionUpdate) ClearMessage() *TaskExecutionUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *TaskExecutionUpdate) SetAttempt(v int32) *TaskExecutionUpdate {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *TaskExecutionUpdate) SetNillableAttempt(v *int32) *TaskExecutionUpdate {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *TaskExecutionUpdate) AddAttempt(v int32) *TaskExecutionUpdate {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *TaskExecutionUpdate) SetDurationMs(v int64) *TaskExecutionUpdate {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *TaskExecutionUpdate) SetNillableDurationMs(v *int64) *TaskExecutionUpdate {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *TaskExecutionUpdate) AddDurationMs(v int64) *TaskExecutionUpdate {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *TaskExecutionUpdate) SetStartedAt(v time.Time) *TaskExecutionUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *TaskExecutionUpdate) SetNillableStartedAt(v *time.Time) *TaskExecutionUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *TaskExecutionUpdate) SetFinishedAt(v time.Time) *TaskExecutionUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *TaskExecutionUpdate) SetNillableFinishedAt(v *time.Time) *TaskExecutionUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *TaskExecutionUpdate) ClearFinishedAt() *TaskExecutionUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TaskExecutionUpdate) SetTenantID(v uint32) *TaskExecutionUpdate {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TaskExecutionUpdate) SetNillableTenantID(v *uint32) *TaskExecutionUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *TaskExecutionUpdate) AddTenantID(v int32) *TaskExecutionUpdate {
	_u.mutation.AddTenantID(v)
	return _u
}

// Mutation returns the TaskExecutionMutation object of the builder.
func (_u *TaskExecutionUpdate) Mutation() *TaskExecutionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TaskExecutionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskExecutionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TaskExecutionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskExecutionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskExecutionUpdate) check() error {
	if v, ok := _u.mutation.ExecutionID(); ok {
		if err := taskexecution.ExecutionIDValidator(v); err != nil {
			return &ValidationError{Name: "execution_id", err: fmt.Errorf(`ent: validator failed for field "TaskExecution.execution_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskType(); ok {
		if err := taskexecution.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "TaskExecution.task_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModuleID(); ok {
		if err := taskexecution.ModuleIDValidator(v); err != nil {
			return &ValidationError{Name: "module_id", err: fmt.Errorf(`ent: validator failed for field "TaskExecution.module_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := taskexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TaskExecution.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TaskExecutionUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TaskExecutionUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TaskExecutionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskexecution.Table, taskexecution.Columns, sqlgraph.NewFieldSpec(taskexecution.FieldID, field.TypeUint32))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExecutionID(); ok {
		_spec.SetField(taskexecution.FieldExecutionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskType(); ok {
		_spec.SetField(taskexecution.FieldTaskType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModuleID(); ok {
		_spec.SetField(taskexecution.FieldModuleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(taskexecution.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(taskexecution.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(taskexecution.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(taskexecution.FieldAttempt, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(taskexecution.FieldAttempt, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(taskexecution.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(taskexecution.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(taskexecution.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(taskexecution.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(taskexecution.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(taskexecution.FieldTenantID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(taskexecution.FieldTenantID, field.TypeUint32, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskexecution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TaskExecutionUpdateOne is the builder for updating a single TaskExecution entity.
type TaskExecutionUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *TaskExecutionMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetExecutionID sets the "execution_id" field.
func (_u *TaskExecutionUpdateOne) SetExecutionID(v string) *TaskExecutionUpdateOne {
	_u.mutation.SetExecutionID(v)
	return _u
}

// SetNillableExecutionID sets the "execution_id" field if the given value is not nil.
func (_u *TaskExecutionUpdateOne) SetNillableExecutionID(v *string) *TaskExecutionUpdateOne {
	if v != nil {
		_u.SetExecutionID(*v)
	}
	return _u
}

// SetTaskType sets the "task_type" field.
func (_u *TaskExecutionUpdateOne) SetTaskType(v string) *TaskExecutionUpdateOne {
	_u.mutation.SetTaskType(v)
	return _u
}

// SetNillableTaskType sets the "task_type" field if the given value is not nil.
func (_u *TaskExecutionUpdateOne) SetNillableTaskType(v *string) *TaskExecutionUpdateOne {
	if v != nil {
		_u.SetTaskType(*v)
	}
	return _u
}

// SetModuleID sets the "module_id" field.
func (_u *TaskExecutionUpdateOne) SetModuleID(v string) *TaskExecutionUpdateOne {
	_u.mutation.SetModuleID(v)
	return _u
}

// SetNillableModuleID sets the "module_id" field if the given value is not nil.
func (_u *TaskExecutionUpdateOne) SetNillableModuleID(v *string) *TaskExecutionUpdateOne {
	if v != nil {
		_u.SetModuleID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *TaskExecutionUpdateOne) SetStatus(v string) *TaskExecutionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *TaskExecutionUpdateOne) SetNillableStatus(v *string) *TaskExecutionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *TaskExecutionUpdateOne) SetMessage(v string) *TaskExecutionUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *TaskExecutionUpdateOne) SetNillableMessage(v *string) *TaskExecutionUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *TaskExecutionUpdateOne) ClearMessage() *TaskExecutionUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *TaskExecutionUpdateOne) SetAttempt(v int32) *TaskExecutionUpdateOne {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *TaskExecutionUpdateOne) SetNillableAttempt(v *int32) *TaskExecutionUpdateOne {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *TaskExecutionUpdateOne) AddAttempt(v int32) *TaskExecutionUpdateOne {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetDurationMs sets the "duration_ms" field.
func (_u *TaskExecutionUpdateOne) SetDurationMs(v int64) *TaskExecutionUpdateOne {
	_u.mutation.ResetDurationMs()
	_u.mutation.SetDurationMs(v)
	return _u
}

// SetNillableDurationMs sets the "duration_ms" field if the given value is not nil.
func (_u *TaskExecutionUpdateOne) SetNillableDurationMs(v *int64) *TaskExecutionUpdateOne {
	if v != nil {
		_u.SetDurationMs(*v)
	}
	return _u
}

// AddDurationMs adds value to the "duration_ms" field.
func (_u *TaskExecutionUpdateOne) AddDurationMs(v int64) *TaskExecutionUpdateOne {
	_u.mutation.AddDurationMs(v)
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *TaskExecutionUpdateOne) SetStartedAt(v time.Time) *TaskExecutionUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *TaskExecutionUpdateOne) SetNillableStartedAt(v *time.Time) *TaskExecutionUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *TaskExecutionUpdateOne) SetFinishedAt(v time.Time) *TaskExecutionUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *TaskExecutionUpdateOne) SetNillableFinishedAt(v *time.Time) *TaskExecutionUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *TaskExecutionUpdateOne) ClearFinishedAt() *TaskExecutionUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *TaskExecutionUpdateOne) SetTenantID(v uint32) *TaskExecutionUpdateOne {
	_u.mutation.ResetTenantID()
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *TaskExecutionUpdateOne) SetNillableTenantID(v *uint32) *TaskExecutionUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// AddTenantID adds value to the "tenant_id" field.
func (_u *TaskExecutionUpdateOne) AddTenantID(v int32) *TaskExecutionUpdateOne {
	_u.mutation.AddTenantID(v)
	return _u
}

// Mutation returns the TaskExecutionMutation object of the builder.
func (_u *TaskExecutionUpdateOne) Mutation() *TaskExecutionMutation {
	return _u.mutation
}

// Where appends a list predicates to the TaskExecutionUpdate builder.
func (_u *TaskExecutionUpdateOne) Where(ps ...predicate.TaskExecution) *TaskExecutionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TaskExecutionUpdateOne) Select(field string, fields ...string) *TaskExecutionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TaskExecution entity.
func (_u *TaskExecutionUpdateOne) Save(ctx context.Context) (*TaskExecution, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TaskExecutionUpdateOne) SaveX(ctx context.Context) *TaskExecution {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TaskExecutionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TaskExecutionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TaskExecutionUpdateOne) check() error {
	if v, ok := _u.mutation.ExecutionID(); ok {
		if err := taskexecution.ExecutionIDValidator(v); err != nil {
			return &ValidationError{Name: "execution_id", err: fmt.Errorf(`ent: validator failed for field "TaskExecution.execution_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TaskType(); ok {
		if err := taskexecution.TaskTypeValidator(v); err != nil {
			return &ValidationError{Name: "task_type", err: fmt.Errorf(`ent: validator failed for field "TaskExecution.task_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ModuleID(); ok {
		if err := taskexecution.ModuleIDValidator(v); err != nil {
			return &ValidationError{Name: "module_id", err: fmt.Errorf(`ent: validator failed for field "TaskExecution.module_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := taskexecution.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "TaskExecution.status": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *TaskExecutionUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *TaskExecutionUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *TaskExecutionUpdateOne) sqlSave(ctx context.Context) (_node *TaskExecution, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(taskexecution.Table, taskexecution.Columns, sqlgraph.NewFieldSpec(taskexecution.FieldID, field.TypeUint32))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TaskExecution.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, taskexecution.FieldID)
		for _, f := range fields {
			if !taskexecution.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != taskexecution.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ExecutionID(); ok {
		_spec.SetField(taskexecution.FieldExecutionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskType(); ok {
		_spec.SetField(taskexecution.FieldTaskType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ModuleID(); ok {
		_spec.SetField(taskexecution.FieldModuleID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(taskexecution.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(taskexecution.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(taskexecution.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(taskexecution.FieldAttempt, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(taskexecution.FieldAttempt, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.DurationMs(); ok {
		_spec.SetField(taskexecution.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDurationMs(); ok {
		_spec.AddField(taskexecution.FieldDurationMs, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(taskexecution.FieldStartedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(taskexecution.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(taskexecution.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(taskexecution.FieldTenantID, field.TypeUint32, value)
	}
	if value, ok := _u.mutation.AddedTenantID(); ok {
		_spec.AddField(taskexecution.FieldTenantID, field.TypeUint32, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &TaskExecution{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{taskexecution.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
