// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/tasktype"
)

// Registered task types from modules
type TaskType struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Globally unique task type name (e.g., paperless:ocr-reindex)
	TaskType string `json:"task_type,omitempty"`
	// Owning module ID (e.g., paperless, deployer)
	ModuleID string `json:"module_id,omitempty"`
	// Human-readable display name
	DisplayName *string `json:"display_name,omitempty"`
	// Description of what this task does
	Description *string `json:"description,omitempty"`
	// JSON Schema for the task payload
	PayloadSchema *string `json:"payload_schema,omitempty"`
	// Default cron expression suggestion
	DefaultCron *string `json:"default_cron,omitempty"`
	// Default max retries
	DefaultMaxRetry int32 `json:"default_max_retry,omitempty"`
	// When this task type was last registered
	RegisteredAt time.Time `json:"registered_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tasktype.FieldID, tasktype.FieldDefaultMaxRetry:
			values[i] = new(sql.NullInt64)
		case tasktype.FieldTaskType, tasktype.FieldModuleID, tasktype.FieldDisplayName, tasktype.FieldDescription, tasktype.FieldPayloadSchema, tasktype.FieldDefaultCron:
			values[i] = new(sql.NullString)
		case tasktype.FieldRegisteredAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskType fields.
func (_m *TaskType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tasktype.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case tasktype.FieldTaskType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_type", values[i])
			} else if value.Valid {
				_m.TaskType = value.String
			}
		case tasktype.FieldModuleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field module_id", values[i])
			} else if value.Valid {
				_m.ModuleID = value.String
			}
		case tasktype.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = new(string)
				*_m.DisplayName = value.String
			}
		case tasktype.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case tasktype.FieldPayloadSchema:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payload_schema", values[i])
			} else if value.Valid {
				_m.PayloadSchema = new(string)
				*_m.PayloadSchema = value.String
			}
		case tasktype.FieldDefaultCron:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_cron", values[i])
			} else if value.Valid {
				_m.DefaultCron = new(string)
				*_m.DefaultCron = value.String
			}
		case tasktype.FieldDefaultMaxRetry:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field default_max_retry", values[i])
			} else if value.Valid {
				_m.DefaultMaxRetry = int32(value.Int64)
			}
		case tasktype.FieldRegisteredAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field registered_at", values[i])
			} else if value.Valid {
				_m.RegisteredAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskType.
// This includes values selected through modifiers, order, etc.
func (_m *TaskType) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TaskType.
// Note that you need to call TaskType.Unwrap() before calling this method if this TaskType
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TaskType) Update() *TaskTypeUpdateOne {
	return NewTaskTypeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TaskType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TaskType) Unwrap() *TaskType {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskType is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TaskType) String() string {
	var builder strings.Builder
	builder.WriteString("TaskType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("task_type=")
	builder.WriteString(_m.TaskType)
	builder.WriteString(", ")
	builder.WriteString("module_id=")
	builder.WriteString(_m.ModuleID)
	builder.WriteString(", ")
	if v := _m.DisplayName; v != nil {
		builder.WriteString("display_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PayloadSchema; v != nil {
		builder.WriteString("payload_schema=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DefaultCron; v != nil {
		builder.WriteString("default_cron=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("default_max_retry=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultMaxRetry))
	builder.WriteString(", ")
	builder.WriteString("registered_at=")
	builder.WriteString(_m.RegisteredAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TaskTypes is a parsable slice of TaskType.
type TaskTypes []*TaskType
