// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/taskexecution"
)

// Task execution history
type TaskExecution struct {
	config `json:"-"`
	// ID of the ent.
	// id
	ID uint32 `json:"id,omitempty"`
	// Unique execution ID (UUID)
	ExecutionID string `json:"execution_id,omitempty"`
	// Task type name (e.g., backup:cleanup-old)
	TaskType string `json:"task_type,omitempty"`
	// Module that executed the task
	ModuleID string `json:"module_id,omitempty"`
	// Execution status: success, failed, running
	Status string `json:"status,omitempty"`
	// Execution result or error message
	Message *string `json:"message,omitempty"`
	// Attempt number
	Attempt int32 `json:"attempt,omitempty"`
	// Execution duration in milliseconds
	DurationMs int64 `json:"duration_ms,omitempty"`
	// When execution started
	StartedAt time.Time `json:"started_at,omitempty"`
	// When execution finished
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// Tenant context
	TenantID     uint32 `json:"tenant_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TaskExecution) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case taskexecution.FieldID, taskexecution.FieldAttempt, taskexecution.FieldDurationMs, taskexecution.FieldTenantID:
			values[i] = new(sql.NullInt64)
		case taskexecution.FieldExecutionID, taskexecution.FieldTaskType, taskexecution.FieldModuleID, taskexecution.FieldStatus, taskexecution.FieldMessage:
			values[i] = new(sql.NullString)
		case taskexecution.FieldStartedAt, taskexecution.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TaskExecution fields.
func (_m *TaskExecution) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case taskexecution.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint32(value.Int64)
		case taskexecution.FieldExecutionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field execution_id", values[i])
			} else if value.Valid {
				_m.ExecutionID = value.String
			}
		case taskexecution.FieldTaskType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field task_type", values[i])
			} else if value.Valid {
				_m.TaskType = value.String
			}
		case taskexecution.FieldModuleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field module_id", values[i])
			} else if value.Valid {
				_m.ModuleID = value.String
			}
		case taskexecution.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case taskexecution.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = new(string)
				*_m.Message = value.String
			}
		case taskexecution.FieldAttempt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt", values[i])
			} else if value.Valid {
				_m.Attempt = int32(value.Int64)
			}
		case taskexecution.FieldDurationMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_ms", values[i])
			} else if value.Valid {
				_m.DurationMs = value.Int64
			}
		case taskexecution.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case taskexecution.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case taskexecution.FieldTenantID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				_m.TenantID = uint32(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TaskExecution.
// This includes values selected through modifiers, order, etc.
func (_m *TaskExecution) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this TaskExecution.
// Note that you need to call TaskExecution.Unwrap() before calling this method if this TaskExecution
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TaskExecution) Update() *TaskExecutionUpdateOne {
	return NewTaskExecutionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TaskExecution entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TaskExecution) Unwrap() *TaskExecution {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TaskExecution is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TaskExecution) String() string {
	var builder strings.Builder
	builder.WriteString("TaskExecution(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("execution_id=")
	builder.WriteString(_m.ExecutionID)
	builder.WriteString(", ")
	builder.WriteString("task_type=")
	builder.WriteString(_m.TaskType)
	builder.WriteString(", ")
	builder.WriteString("module_id=")
	builder.WriteString(_m.ModuleID)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Message; v != nil {
		builder.WriteString("message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("attempt=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempt))
	builder.WriteString(", ")
	builder.WriteString("duration_ms=")
	builder.WriteString(fmt.Sprintf("%v", _m.DurationMs))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteByte(')')
	return builder.String()
}

// TaskExecutions is a parsable slice of TaskExecution.
type TaskExecutions []*TaskExecution
