// Code generated by ent, DO NOT EDIT.

package tasktype

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the tasktype type in the database.
	Label = "task_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskType holds the string denoting the task_type field in the database.
	FieldTaskType = "task_type"
	// FieldModuleID holds the string denoting the module_id field in the database.
	FieldModuleID = "module_id"
	// FieldDisplayName holds the string denoting the display_name field in the database.
	FieldDisplayName = "display_name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldPayloadSchema holds the string denoting the payload_schema field in the database.
	FieldPayloadSchema = "payload_schema"
	// FieldDefaultCron holds the string denoting the default_cron field in the database.
	FieldDefaultCron = "default_cron"
	// FieldDefaultMaxRetry holds the string denoting the default_max_retry field in the database.
	FieldDefaultMaxRetry = "default_max_retry"
	// FieldRegisteredAt holds the string denoting the registered_at field in the database.
	FieldRegisteredAt = "registered_at"
	// Table holds the table name of the tasktype in the database.
	Table = "scheduler_task_types"
)

// Columns holds all SQL columns for tasktype fields.
var Columns = []string{
	FieldID,
	FieldTaskType,
	FieldModuleID,
	FieldDisplayName,
	FieldDescription,
	FieldPayloadSchema,
	FieldDefaultCron,
	FieldDefaultMaxRetry,
	FieldRegisteredAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TaskTypeValidator is a validator for the "task_type" field. It is called by the builders before save.
	TaskTypeValidator func(string) error
	// ModuleIDValidator is a validator for the "module_id" field. It is called by the builders before save.
	ModuleIDValidator func(string) error
	// DefaultDefaultMaxRetry holds the default value on creation for the "default_max_retry" field.
	DefaultDefaultMaxRetry int32
	// DefaultRegisteredAt holds the default value on creation for the "registered_at" field.
	DefaultRegisteredAt func() time.Time
)

// OrderOption defines the ordering options for the TaskType queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTaskType orders the results by the task_type field.
func ByTaskType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskType, opts...).ToFunc()
}

// ByModuleID orders the results by the module_id field.
func ByModuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModuleID, opts...).ToFunc()
}

// ByDisplayName orders the results by the display_name field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByPayloadSchema orders the results by the payload_schema field.
func ByPayloadSchema(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadSchema, opts...).ToFunc()
}

// ByDefaultCron orders the results by the default_cron field.
func ByDefaultCron(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultCron, opts...).ToFunc()
}

// ByDefaultMaxRetry orders the results by the default_max_retry field.
func ByDefaultMaxRetry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultMaxRetry, opts...).ToFunc()
}

// ByRegisteredAt orders the results by the registered_at field.
func ByRegisteredAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegisteredAt, opts...).ToFunc()
}
