// Code generated by ent, DO NOT EDIT.

package tasktype

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TaskType {
	return predicate.TaskType(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TaskType {
	return predicate.TaskType(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TaskType {
	return predicate.TaskType(sql.FieldLTE(FieldID, id))
}

// TaskType applies equality check predicate on the "task_type" field. It's identical to TaskTypeEQ.
func TaskType(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldTaskType, v))
}

// ModuleID applies equality check predicate on the "module_id" field. It's identical to ModuleIDEQ.
func ModuleID(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldModuleID, v))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldDisplayName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldDescription, v))
}

// PayloadSchema applies equality check predicate on the "payload_schema" field. It's identical to PayloadSchemaEQ.
func PayloadSchema(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldPayloadSchema, v))
}

// DefaultCron applies equality check predicate on the "default_cron" field. It's identical to DefaultCronEQ.
func DefaultCron(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldDefaultCron, v))
}

// DefaultMaxRetry applies equality check predicate on the "default_max_retry" field. It's identical to DefaultMaxRetryEQ.
func DefaultMaxRetry(v int32) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldDefaultMaxRetry, v))
}

// RegisteredAt applies equality check predicate on the "registered_at" field. It's identical to RegisteredAtEQ.
func RegisteredAt(v time.Time) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldRegisteredAt, v))
}

// TaskTypeEQ applies the EQ predicate on the "task_type" field.
func TaskTypeEQ(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldTaskType, v))
}

// TaskTypeNEQ applies the NEQ predicate on the "task_type" field.
func TaskTypeNEQ(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldNEQ(FieldTaskType, v))
}

// TaskTypeIn applies the In predicate on the "task_type" field.
func TaskTypeIn(vs ...string) predicate.TaskType {
	return predicate.TaskType(sql.FieldIn(FieldTaskType, vs...))
}

// TaskTypeNotIn applies the NotIn predicate on the "task_type" field.
func TaskTypeNotIn(vs ...string) predicate.TaskType {
	return predicate.TaskType(sql.FieldNotIn(FieldTaskType, vs...))
}

// TaskTypeGT applies the GT predicate on the "task_type" field.
func TaskTypeGT(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldGT(FieldTaskType, v))
}

// TaskTypeGTE applies the GTE predicate on the "task_type" field.
func TaskTypeGTE(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldGTE(FieldTaskType, v))
}

// TaskTypeLT applies the LT predicate on the "task_type" field.
func TaskTypeLT(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldLT(FieldTaskType, v))
}

// TaskTypeLTE applies the LTE predicate on the "task_type" field.
func TaskTypeLTE(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldLTE(FieldTaskType, v))
}

// TaskTypeContains applies the Contains predicate on the "task_type" field.
func TaskTypeContains(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldContains(FieldTaskType, v))
}

// TaskTypeHasPrefix applies the HasPrefix predicate on the "task_type" field.
func TaskTypeHasPrefix(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldHasPrefix(FieldTaskType, v))
}

// TaskTypeHasSuffix applies the HasSuffix predicate on the "task_type" field.
func TaskTypeHasSuffix(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldHasSuffix(FieldTaskType, v))
}

// TaskTypeEqualFold applies the EqualFold predicate on the "task_type" field.
func TaskTypeEqualFold(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEqualFold(FieldTaskType, v))
}

// TaskTypeContainsFold applies the ContainsFold predicate on the "task_type" field.
func TaskTypeContainsFold(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldContainsFold(FieldTaskType, v))
}

// ModuleIDEQ applies the EQ predicate on the "module_id" field.
func ModuleIDEQ(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldModuleID, v))
}

// ModuleIDNEQ applies the NEQ predicate on the "module_id" field.
func ModuleIDNEQ(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldNEQ(FieldModuleID, v))
}

// ModuleIDIn applies the In predicate on the "module_id" field.
func ModuleIDIn(vs ...string) predicate.TaskType {
	return predicate.TaskType(sql.FieldIn(FieldModuleID, vs...))
}

// ModuleIDNotIn applies the NotIn predicate on the "module_id" field.
func ModuleIDNotIn(vs ...string) predicate.TaskType {
	return predicate.TaskType(sql.FieldNotIn(FieldModuleID, vs...))
}

// ModuleIDGT applies the GT predicate on the "module_id" field.
func ModuleIDGT(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldGT(FieldModuleID, v))
}

// ModuleIDGTE applies the GTE predicate on the "module_id" field.
func ModuleIDGTE(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldGTE(FieldModuleID, v))
}

// ModuleIDLT applies the LT predicate on the "module_id" field.
func ModuleIDLT(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldLT(FieldModuleID, v))
}

// ModuleIDLTE applies the LTE predicate on the "module_id" field.
func ModuleIDLTE(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldLTE(FieldModuleID, v))
}

// ModuleIDContains applies the Contains predicate on the "module_id" field.
func ModuleIDContains(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldContains(FieldModuleID, v))
}

// ModuleIDHasPrefix applies the HasPrefix predicate on the "module_id" field.
func ModuleIDHasPrefix(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldHasPrefix(FieldModuleID, v))
}

// ModuleIDHasSuffix applies the HasSuffix predicate on the "module_id" field.
func ModuleIDHasSuffix(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldHasSuffix(FieldModuleID, v))
}

// ModuleIDEqualFold applies the EqualFold predicate on the "module_id" field.
func ModuleIDEqualFold(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEqualFold(FieldModuleID, v))
}

// ModuleIDContainsFold applies the ContainsFold predicate on the "module_id" field.
func ModuleIDContainsFold(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldContainsFold(FieldModuleID, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.TaskType {
	return predicate.TaskType(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.TaskType {
	return predicate.TaskType(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameIsNil applies the IsNil predicate on the "display_name" field.
func DisplayNameIsNil() predicate.TaskType {
	return predicate.TaskType(sql.FieldIsNull(FieldDisplayName))
}

// DisplayNameNotNil applies the NotNil predicate on the "display_name" field.
func DisplayNameNotNil() predicate.TaskType {
	return predicate.TaskType(sql.FieldNotNull(FieldDisplayName))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldContainsFold(FieldDisplayName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.TaskType {
	return predicate.TaskType(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.TaskType {
	return predicate.TaskType(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.TaskType {
	return predicate.TaskType(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.TaskType {
	return predicate.TaskType(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldContainsFold(FieldDescription, v))
}

// PayloadSchemaEQ applies the EQ predicate on the "payload_schema" field.
func PayloadSchemaEQ(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldPayloadSchema, v))
}

// PayloadSchemaNEQ applies the NEQ predicate on the "payload_schema" field.
func PayloadSchemaNEQ(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldNEQ(FieldPayloadSchema, v))
}

// PayloadSchemaIn applies the In predicate on the "payload_schema" field.
func PayloadSchemaIn(vs ...string) predicate.TaskType {
	return predicate.TaskType(sql.FieldIn(FieldPayloadSchema, vs...))
}

// PayloadSchemaNotIn applies the NotIn predicate on the "payload_schema" field.
func PayloadSchemaNotIn(vs ...string) predicate.TaskType {
	return predicate.TaskType(sql.FieldNotIn(FieldPayloadSchema, vs...))
}

// PayloadSchemaGT applies the GT predicate on the "payload_schema" field.
func PayloadSchemaGT(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldGT(FieldPayloadSchema, v))
}

// PayloadSchemaGTE applies the GTE predicate on the "payload_schema" field.
func PayloadSchemaGTE(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldGTE(FieldPayloadSchema, v))
}

// PayloadSchemaLT applies the LT predicate on the "payload_schema" field.
func PayloadSchemaLT(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldLT(FieldPayloadSchema, v))
}

// PayloadSchemaLTE applies the LTE predicate on the "payload_schema" field.
func PayloadSchemaLTE(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldLTE(FieldPayloadSchema, v))
}

// PayloadSchemaContains applies the Contains predicate on the "payload_schema" field.
func PayloadSchemaContains(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldContains(FieldPayloadSchema, v))
}

// PayloadSchemaHasPrefix applies the HasPrefix predicate on the "payload_schema" field.
func PayloadSchemaHasPrefix(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldHasPrefix(FieldPayloadSchema, v))
}

// PayloadSchemaHasSuffix applies the HasSuffix predicate on the "payload_schema" field.
func PayloadSchemaHasSuffix(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldHasSuffix(FieldPayloadSchema, v))
}

// PayloadSchemaIsNil applies the IsNil predicate on the "payload_schema" field.
func PayloadSchemaIsNil() predicate.TaskType {
	return predicate.TaskType(sql.FieldIsNull(FieldPayloadSchema))
}

// PayloadSchemaNotNil applies the NotNil predicate on the "payload_schema" field.
func PayloadSchemaNotNil() predicate.TaskType {
	return predicate.TaskType(sql.FieldNotNull(FieldPayloadSchema))
}

// PayloadSchemaEqualFold applies the EqualFold predicate on the "payload_schema" field.
func PayloadSchemaEqualFold(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEqualFold(FieldPayloadSchema, v))
}

// PayloadSchemaContainsFold applies the ContainsFold predicate on the "payload_schema" field.
func PayloadSchemaContainsFold(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldContainsFold(FieldPayloadSchema, v))
}

// DefaultCronEQ applies the EQ predicate on the "default_cron" field.
func DefaultCronEQ(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldDefaultCron, v))
}

// DefaultCronNEQ applies the NEQ predicate on the "default_cron" field.
func DefaultCronNEQ(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldNEQ(FieldDefaultCron, v))
}

// DefaultCronIn applies the In predicate on the "default_cron" field.
func DefaultCronIn(vs ...string) predicate.TaskType {
	return predicate.TaskType(sql.FieldIn(FieldDefaultCron, vs...))
}

// DefaultCronNotIn applies the NotIn predicate on the "default_cron" field.
func DefaultCronNotIn(vs ...string) predicate.TaskType {
	return predicate.TaskType(sql.FieldNotIn(FieldDefaultCron, vs...))
}

// DefaultCronGT applies the GT predicate on the "default_cron" field.
func DefaultCronGT(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldGT(FieldDefaultCron, v))
}

// DefaultCronGTE applies the GTE predicate on the "default_cron" field.
func DefaultCronGTE(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldGTE(FieldDefaultCron, v))
}

// DefaultCronLT applies the LT predicate on the "default_cron" field.
func DefaultCronLT(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldLT(FieldDefaultCron, v))
}

// DefaultCronLTE applies the LTE predicate on the "default_cron" field.
func DefaultCronLTE(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldLTE(FieldDefaultCron, v))
}

// DefaultCronContains applies the Contains predicate on the "default_cron" field.
func DefaultCronContains(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldContains(FieldDefaultCron, v))
}

// DefaultCronHasPrefix applies the HasPrefix predicate on the "default_cron" field.
func DefaultCronHasPrefix(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldHasPrefix(FieldDefaultCron, v))
}

// DefaultCronHasSuffix applies the HasSuffix predicate on the "default_cron" field.
func DefaultCronHasSuffix(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldHasSuffix(FieldDefaultCron, v))
}

// DefaultCronIsNil applies the IsNil predicate on the "default_cron" field.
func DefaultCronIsNil() predicate.TaskType {
	return predicate.TaskType(sql.FieldIsNull(FieldDefaultCron))
}

// DefaultCronNotNil applies the NotNil predicate on the "default_cron" field.
func DefaultCronNotNil() predicate.TaskType {
	return predicate.TaskType(sql.FieldNotNull(FieldDefaultCron))
}

// DefaultCronEqualFold applies the EqualFold predicate on the "default_cron" field.
func DefaultCronEqualFold(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldEqualFold(FieldDefaultCron, v))
}

// DefaultCronContainsFold applies the ContainsFold predicate on the "default_cron" field.
func DefaultCronContainsFold(v string) predicate.TaskType {
	return predicate.TaskType(sql.FieldContainsFold(FieldDefaultCron, v))
}

// DefaultMaxRetryEQ applies the EQ predicate on the "default_max_retry" field.
func DefaultMaxRetryEQ(v int32) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldDefaultMaxRetry, v))
}

// DefaultMaxRetryNEQ applies the NEQ predicate on the "default_max_retry" field.
func DefaultMaxRetryNEQ(v int32) predicate.TaskType {
	return predicate.TaskType(sql.FieldNEQ(FieldDefaultMaxRetry, v))
}

// DefaultMaxRetryIn applies the In predicate on the "default_max_retry" field.
func DefaultMaxRetryIn(vs ...int32) predicate.TaskType {
	return predicate.TaskType(sql.FieldIn(FieldDefaultMaxRetry, vs...))
}

// DefaultMaxRetryNotIn applies the NotIn predicate on the "default_max_retry" field.
func DefaultMaxRetryNotIn(vs ...int32) predicate.TaskType {
	return predicate.TaskType(sql.FieldNotIn(FieldDefaultMaxRetry, vs...))
}

// DefaultMaxRetryGT applies the GT predicate on the "default_max_retry" field.
func DefaultMaxRetryGT(v int32) predicate.TaskType {
	return predicate.TaskType(sql.FieldGT(FieldDefaultMaxRetry, v))
}

// DefaultMaxRetryGTE applies the GTE predicate on the "default_max_retry" field.
func DefaultMaxRetryGTE(v int32) predicate.TaskType {
	return predicate.TaskType(sql.FieldGTE(FieldDefaultMaxRetry, v))
}

// DefaultMaxRetryLT applies the LT predicate on the "default_max_retry" field.
func DefaultMaxRetryLT(v int32) predicate.TaskType {
	return predicate.TaskType(sql.FieldLT(FieldDefaultMaxRetry, v))
}

// DefaultMaxRetryLTE applies the LTE predicate on the "default_max_retry" field.
func DefaultMaxRetryLTE(v int32) predicate.TaskType {
	return predicate.TaskType(sql.FieldLTE(FieldDefaultMaxRetry, v))
}

// RegisteredAtEQ applies the EQ predicate on the "registered_at" field.
func RegisteredAtEQ(v time.Time) predicate.TaskType {
	return predicate.TaskType(sql.FieldEQ(FieldRegisteredAt, v))
}

// RegisteredAtNEQ applies the NEQ predicate on the "registered_at" field.
func RegisteredAtNEQ(v time.Time) predicate.TaskType {
	return predicate.TaskType(sql.FieldNEQ(FieldRegisteredAt, v))
}

// RegisteredAtIn applies the In predicate on the "registered_at" field.
func RegisteredAtIn(vs ...time.Time) predicate.TaskType {
	return predicate.TaskType(sql.FieldIn(FieldRegisteredAt, vs...))
}

// RegisteredAtNotIn applies the NotIn predicate on the "registered_at" field.
func RegisteredAtNotIn(vs ...time.Time) predicate.TaskType {
	return predicate.TaskType(sql.FieldNotIn(FieldRegisteredAt, vs...))
}

// RegisteredAtGT applies the GT predicate on the "registered_at" field.
func RegisteredAtGT(v time.Time) predicate.TaskType {
	return predicate.TaskType(sql.FieldGT(FieldRegisteredAt, v))
}

// RegisteredAtGTE applies the GTE predicate on the "registered_at" field.
func RegisteredAtGTE(v time.Time) predicate.TaskType {
	return predicate.TaskType(sql.FieldGTE(FieldRegisteredAt, v))
}

// RegisteredAtLT applies the LT predicate on the "registered_at" field.
func RegisteredAtLT(v time.Time) predicate.TaskType {
	return predicate.TaskType(sql.FieldLT(FieldRegisteredAt, v))
}

// RegisteredAtLTE applies the LTE predicate on the "registered_at" field.
func RegisteredAtLTE(v time.Time) predicate.TaskType {
	return predicate.TaskType(sql.FieldLTE(FieldRegisteredAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TaskType) predicate.TaskType {
	return predicate.TaskType(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TaskType) predicate.TaskType {
	return predicate.TaskType(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TaskType) predicate.TaskType {
	return predicate.TaskType(sql.NotPredicates(p))
}
