// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskExecution is the predicate function for taskexecution builders.
type TaskExecution func(*sql.Selector)

// TaskType is the predicate function for tasktype builders.
type TaskType func(*sql.Selector)
