// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SchedulerTasksColumns holds the columns for the "scheduler_tasks" table.
	SchedulerTasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "created_at", Type: field.TypeTime, Nullable: true, Comment: "创建时间"},
		{Name: "updated_at", Type: field.TypeTime, Nullable: true, Comment: "更新时间"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "删除时间"},
		{Name: "created_by", Type: field.TypeUint32, Nullable: true, Comment: "创建者ID"},
		{Name: "updated_by", Type: field.TypeUint32, Nullable: true, Comment: "更新者ID"},
		{Name: "deleted_by", Type: field.TypeUint32, Nullable: true, Comment: "删除者ID"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Comment: "备注"},
		{Name: "tenant_id", Type: field.TypeUint32, Nullable: true, Comment: "租户ID", Default: 0},
		{Name: "type", Type: field.TypeEnum, Nullable: true, Comment: "Task type", Enums: []string{"PERIODIC", "DELAY", "WAIT_RESULT"}, Default: "PERIODIC"},
		{Name: "type_name", Type: field.TypeString, Nullable: true, Comment: "Task execution type name (e.g., paperless:ocr-reindex)"},
		{Name: "module_id", Type: field.TypeString, Nullable: true, Comment: "Owning module ID (resolved from task type registry)"},
		{Name: "task_payload", Type: field.TypeString, Nullable: true, Comment: "Task data in JSON format", SchemaType: map[string]string{"mysql": "json", "postgres": "jsonb"}},
		{Name: "cron_spec", Type: field.TypeString, Nullable: true, Comment: "Cron expression for periodic scheduling"},
		{Name: "task_options", Type: field.TypeJSON, Nullable: true, Comment: "Task execution options"},
		{Name: "enable", Type: field.TypeBool, Nullable: true, Comment: "Enable/disable task", Default: false},
		{Name: "last_run_at", Type: field.TypeTime, Nullable: true, Comment: "When the task last executed"},
		{Name: "last_run_status", Type: field.TypeString, Nullable: true, Comment: "Last execution status: success, failed, running"},
		{Name: "last_run_message", Type: field.TypeString, Nullable: true, Comment: "Last execution result or error message"},
		{Name: "run_count", Type: field.TypeInt32, Comment: "Total execution count", Default: 0},
	}
	// SchedulerTasksTable holds the schema information for the "scheduler_tasks" table.
	SchedulerTasksTable = &schema.Table{
		Name:       "scheduler_tasks",
		Comment:    "Scheduled tasks",
		Columns:    SchedulerTasksColumns,
		PrimaryKey: []*schema.Column{SchedulerTasksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_scheduler_task_tenant_type_name",
				Unique:  true,
				Columns: []*schema.Column{SchedulerTasksColumns[8], SchedulerTasksColumns[10]},
			},
			{
				Name:    "idx_scheduler_task_tenant_type",
				Unique:  false,
				Columns: []*schema.Column{SchedulerTasksColumns[8], SchedulerTasksColumns[9]},
			},
			{
				Name:    "idx_scheduler_task_tenant_enable_created_at",
				Unique:  false,
				Columns: []*schema.Column{SchedulerTasksColumns[8], SchedulerTasksColumns[15], SchedulerTasksColumns[1]},
			},
			{
				Name:    "idx_scheduler_task_tenant_created_by_created_at",
				Unique:  false,
				Columns: []*schema.Column{SchedulerTasksColumns[8], SchedulerTasksColumns[4], SchedulerTasksColumns[1]},
			},
			{
				Name:    "idx_scheduler_task_tenant_created_at",
				Unique:  false,
				Columns: []*schema.Column{SchedulerTasksColumns[8], SchedulerTasksColumns[1]},
			},
		},
	}
	// SchedulerTaskExecutionsColumns holds the columns for the "scheduler_task_executions" table.
	SchedulerTaskExecutionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUint32, Increment: true, Comment: "id"},
		{Name: "execution_id", Type: field.TypeString, Unique: true, Comment: "Unique execution ID (UUID)"},
		{Name: "task_type", Type: field.TypeString, Comment: "Task type name (e.g., backup:cleanup-old)"},
		{Name: "module_id", Type: field.TypeString, Comment: "Module that executed the task"},
		{Name: "status", Type: field.TypeString, Comment: "Execution status: success, failed, running"},
		{Name: "message", Type: field.TypeString, Nullable: true, Comment: "Execution result or error message"},
		{Name: "attempt", Type: field.TypeInt32, Comment: "Attempt number", Default: 1},
		{Name: "duration_ms", Type: field.TypeInt64, Comment: "Execution duration in milliseconds", Default: 0},
		{Name: "started_at", Type: field.TypeTime, Comment: "When execution started"},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true, Comment: "When execution finished"},
		{Name: "tenant_id", Type: field.TypeUint32, Comment: "Tenant context", Default: 0},
	}
	// SchedulerTaskExecutionsTable holds the schema information for the "scheduler_task_executions" table.
	SchedulerTaskExecutionsTable = &schema.Table{
		Name:       "scheduler_task_executions",
		Comment:    "Task execution history",
		Columns:    SchedulerTaskExecutionsColumns,
		PrimaryKey: []*schema.Column{SchedulerTaskExecutionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_scheduler_exec_task_started",
				Unique:  false,
				Columns: []*schema.Column{SchedulerTaskExecutionsColumns[2], SchedulerTaskExecutionsColumns[8]},
			},
			{
				Name:    "idx_scheduler_exec_module_started",
				Unique:  false,
				Columns: []*schema.Column{SchedulerTaskExecutionsColumns[3], SchedulerTaskExecutionsColumns[8]},
			},
			{
				Name:    "idx_scheduler_exec_status",
				Unique:  false,
				Columns: []*schema.Column{SchedulerTaskExecutionsColumns[4]},
			},
		},
	}
	// SchedulerTaskTypesColumns holds the columns for the "scheduler_task_types" table.
	SchedulerTaskTypesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "task_type", Type: field.TypeString, Unique: true, Comment: "Globally unique task type name (e.g., paperless:ocr-reindex)"},
		{Name: "module_id", Type: field.TypeString, Comment: "Owning module ID (e.g., paperless, deployer)"},
		{Name: "display_name", Type: field.TypeString, Nullable: true, Comment: "Human-readable display name"},
		{Name: "description", Type: field.TypeString, Nullable: true, Comment: "Description of what this task does"},
		{Name: "payload_schema", Type: field.TypeString, Nullable: true, Comment: "JSON Schema for the task payload"},
		{Name: "default_cron", Type: field.TypeString, Nullable: true, Comment: "Default cron expression suggestion"},
		{Name: "default_max_retry", Type: field.TypeInt32, Comment: "Default max retries", Default: 3},
		{Name: "registered_at", Type: field.TypeTime, Comment: "When this task type was last registered"},
	}
	// SchedulerTaskTypesTable holds the schema information for the "scheduler_task_types" table.
	SchedulerTaskTypesTable = &schema.Table{
		Name:       "scheduler_task_types",
		Comment:    "Registered task types from modules",
		Columns:    SchedulerTaskTypesColumns,
		PrimaryKey: []*schema.Column{SchedulerTaskTypesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_scheduler_task_type_module",
				Unique:  false,
				Columns: []*schema.Column{SchedulerTaskTypesColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SchedulerTasksTable,
		SchedulerTaskExecutionsTable,
		SchedulerTaskTypesTable,
	}
)

func init() {
	SchedulerTasksTable.Annotation = &entsql.Annotation{
		Table:     "scheduler_tasks",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SchedulerTaskExecutionsTable.Annotation = &entsql.Annotation{
		Table:     "scheduler_task_executions",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
	SchedulerTaskTypesTable.Annotation = &entsql.Annotation{
		Table:     "scheduler_task_types",
		Charset:   "utf8mb4",
		Collation: "utf8mb4_bin",
	}
}
