// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-tangra/go-tangra-scheduler/internal/cert"
	"github.com/go-tangra/go-tangra-scheduler/internal/data"
	"github.com/go-tangra/go-tangra-scheduler/internal/executor"
	"github.com/go-tangra/go-tangra-scheduler/internal/metrics"
	"github.com/go-tangra/go-tangra-scheduler/internal/server"
	"github.com/go-tangra/go-tangra-scheduler/internal/service"
	"github.com/tx7do/kratos-bootstrap/bootstrap"
)

// Injectors from wire.go:

// initApp initializes the Wire provider entry for the kratos application
func initApp(context *bootstrap.Context) (*kratos.App, func(), error) {
	v, err := cert.NewCertManager(context)
	if err != nil {
		return nil, nil, err
	}
	collector := metrics.NewCollector(context)
	entClient, cleanup, err := data.NewEntClient(context)
	if err != nil {
		return nil, nil, err
	}
	taskRepo := data.NewTaskRepo(context, entClient)
	taskExecutionRepo := data.NewTaskExecutionRepo(context, entClient)
	taskTypeRegistry := executor.NewTaskTypeRegistry()
	taskService := service.NewTaskService(context, taskRepo, taskExecutionRepo, taskTypeRegistry)
	taskTypeRepo := data.NewTaskTypeRepo(context, entClient)
	client, err := data.NewRegistrationClient(context)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	moduleDialer := data.NewModuleDialer(context, client)
	moduleConnPool := executor.ProvideModuleConnPool(context, moduleDialer)
	compositeExecutionRecorder := data.NewCompositeExecutionRecorder(taskRepo, taskExecutionRepo)
	remoteExecutor := executor.ProvideRemoteExecutor(context, taskTypeRegistry, moduleConnPool, compositeExecutionRecorder)
	taskTypeService := service.NewTaskTypeService(context, taskTypeRegistry, taskTypeRepo, remoteExecutor)
	backupService := service.NewBackupService(context, entClient)
	grpcServer := server.NewGRPCServer(context, v, collector, taskService, taskTypeService, backupService)
	httpServer := server.NewHTTPServer(context)
	asynqServer, err := server.NewAsynqServer(context, taskService, taskTypeService, remoteExecutor, taskTypeRegistry)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := newApp(context, grpcServer, httpServer, asynqServer, client)
	return app, func() {
		cleanup()
	}, nil
}
