// Code generated by ent, DO NOT EDIT.

package taskexecution

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/go-tangra/go-tangra-scheduler/internal/data/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLTE(FieldID, id))
}

// ExecutionID applies equality check predicate on the "execution_id" field. It's identical to ExecutionIDEQ.
func ExecutionID(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldExecutionID, v))
}

// TaskType applies equality check predicate on the "task_type" field. It's identical to TaskTypeEQ.
func TaskType(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldTaskType, v))
}

// ModuleID applies equality check predicate on the "module_id" field. It's identical to ModuleIDEQ.
func ModuleID(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldModuleID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldStatus, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldMessage, v))
}

// Attempt applies equality check predicate on the "attempt" field. It's identical to AttemptEQ.
func Attempt(v int32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldAttempt, v))
}

// DurationMs applies equality check predicate on the "duration_ms" field. It's identical to DurationMsEQ.
func DurationMs(v int64) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldDurationMs, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldFinishedAt, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldTenantID, v))
}

// ExecutionIDEQ applies the EQ predicate on the "execution_id" field.
func ExecutionIDEQ(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldExecutionID, v))
}

// ExecutionIDNEQ applies the NEQ predicate on the "execution_id" field.
func ExecutionIDNEQ(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNEQ(FieldExecutionID, v))
}

// ExecutionIDIn applies the In predicate on the "execution_id" field.
func ExecutionIDIn(vs ...string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldIn(FieldExecutionID, vs...))
}

// ExecutionIDNotIn applies the NotIn predicate on the "execution_id" field.
func ExecutionIDNotIn(vs ...string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNotIn(FieldExecutionID, vs...))
}

// ExecutionIDGT applies the GT predicate on the "execution_id" field.
func ExecutionIDGT(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGT(FieldExecutionID, v))
}

// ExecutionIDGTE applies the GTE predicate on the "execution_id" field.
func ExecutionIDGTE(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGTE(FieldExecutionID, v))
}

// ExecutionIDLT applies the LT predicate on the "execution_id" field.
func ExecutionIDLT(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLT(FieldExecutionID, v))
}

// ExecutionIDLTE applies the LTE predicate on the "execution_id" field.
func ExecutionIDLTE(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLTE(FieldExecutionID, v))
}

// ExecutionIDContains applies the Contains predicate on the "execution_id" field.
func ExecutionIDContains(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldContains(FieldExecutionID, v))
}

// ExecutionIDHasPrefix applies the HasPrefix predicate on the "execution_id" field.
func ExecutionIDHasPrefix(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldHasPrefix(FieldExecutionID, v))
}

// ExecutionIDHasSuffix applies the HasSuffix predicate on the "execution_id" field.
func ExecutionIDHasSuffix(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldHasSuffix(FieldExecutionID, v))
}

// ExecutionIDEqualFold applies the EqualFold predicate on the "execution_id" field.
func ExecutionIDEqualFold(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEqualFold(FieldExecutionID, v))
}

// ExecutionIDContainsFold applies the ContainsFold predicate on the "execution_id" field.
func ExecutionIDContainsFold(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldContainsFold(FieldExecutionID, v))
}

// TaskTypeEQ applies the EQ predicate on the "task_type" field.
func TaskTypeEQ(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldTaskType, v))
}

// TaskTypeNEQ applies the NEQ predicate on the "task_type" field.
func TaskTypeNEQ(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNEQ(FieldTaskType, v))
}

// TaskTypeIn applies the In predicate on the "task_type" field.
func TaskTypeIn(vs ...string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldIn(FieldTaskType, vs...))
}

// TaskTypeNotIn applies the NotIn predicate on the "task_type" field.
func TaskTypeNotIn(vs ...string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNotIn(FieldTaskType, vs...))
}

// TaskTypeGT applies the GT predicate on the "task_type" field.
func TaskTypeGT(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGT(FieldTaskType, v))
}

// TaskTypeGTE applies the GTE predicate on the "task_type" field.
func TaskTypeGTE(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGTE(FieldTaskType, v))
}

// TaskTypeLT applies the LT predicate on the "task_type" field.
func TaskTypeLT(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLT(FieldTaskType, v))
}

// TaskTypeLTE applies the LTE predicate on the "task_type" field.
func TaskTypeLTE(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLTE(FieldTaskType, v))
}

// TaskTypeContains applies the Contains predicate on the "task_type" field.
func TaskTypeContains(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldContains(FieldTaskType, v))
}

// TaskTypeHasPrefix applies the HasPrefix predicate on the "task_type" field.
func TaskTypeHasPrefix(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldHasPrefix(FieldTaskType, v))
}

// TaskTypeHasSuffix applies the HasSuffix predicate on the "task_type" field.
func TaskTypeHasSuffix(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldHasSuffix(FieldTaskType, v))
}

// TaskTypeEqualFold applies the EqualFold predicate on the "task_type" field.
func TaskTypeEqualFold(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEqualFold(FieldTaskType, v))
}

// TaskTypeContainsFold applies the ContainsFold predicate on the "task_type" field.
func TaskTypeContainsFold(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldContainsFold(FieldTaskType, v))
}

// ModuleIDEQ applies the EQ predicate on the "module_id" field.
func ModuleIDEQ(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldModuleID, v))
}

// ModuleIDNEQ applies the NEQ predicate on the "module_id" field.
func ModuleIDNEQ(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNEQ(FieldModuleID, v))
}

// ModuleIDIn applies the In predicate on the "module_id" field.
func ModuleIDIn(vs ...string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldIn(FieldModuleID, vs...))
}

// ModuleIDNotIn applies the NotIn predicate on the "module_id" field.
func ModuleIDNotIn(vs ...string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNotIn(FieldModuleID, vs...))
}

// ModuleIDGT applies the GT predicate on the "module_id" field.
func ModuleIDGT(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGT(FieldModuleID, v))
}

// ModuleIDGTE applies the GTE predicate on the "module_id" field.
func ModuleIDGTE(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGTE(FieldModuleID, v))
}

// ModuleIDLT applies the LT predicate on the "module_id" field.
func ModuleIDLT(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLT(FieldModuleID, v))
}

// ModuleIDLTE applies the LTE predicate on the "module_id" field.
func ModuleIDLTE(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLTE(FieldModuleID, v))
}

// ModuleIDContains applies the Contains predicate on the "module_id" field.
func ModuleIDContains(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldContains(FieldModuleID, v))
}

// ModuleIDHasPrefix applies the HasPrefix predicate on the "module_id" field.
func ModuleIDHasPrefix(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldHasPrefix(FieldModuleID, v))
}

// ModuleIDHasSuffix applies the HasSuffix predicate on the "module_id" field.
func ModuleIDHasSuffix(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldHasSuffix(FieldModuleID, v))
}

// ModuleIDEqualFold applies the EqualFold predicate on the "module_id" field.
func ModuleIDEqualFold(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEqualFold(FieldModuleID, v))
}

// ModuleIDContainsFold applies the ContainsFold predicate on the "module_id" field.
func ModuleIDContainsFold(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldContainsFold(FieldModuleID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldContainsFold(FieldStatus, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageIsNil applies the IsNil predicate on the "message" field.
func MessageIsNil() predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldIsNull(FieldMessage))
}

// MessageNotNil applies the NotNil predicate on the "message" field.
func MessageNotNil() predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNotNull(FieldMessage))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldContainsFold(FieldMessage, v))
}

// AttemptEQ applies the EQ predicate on the "attempt" field.
func AttemptEQ(v int32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldAttempt, v))
}

// AttemptNEQ applies the NEQ predicate on the "attempt" field.
func AttemptNEQ(v int32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNEQ(FieldAttempt, v))
}

// AttemptIn applies the In predicate on the "attempt" field.
func AttemptIn(vs ...int32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldIn(FieldAttempt, vs...))
}

// AttemptNotIn applies the NotIn predicate on the "attempt" field.
func AttemptNotIn(vs ...int32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNotIn(FieldAttempt, vs...))
}

// AttemptGT applies the GT predicate on the "attempt" field.
func AttemptGT(v int32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGT(FieldAttempt, v))
}

// AttemptGTE applies the GTE predicate on the "attempt" field.
func AttemptGTE(v int32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGTE(FieldAttempt, v))
}

// AttemptLT applies the LT predicate on the "attempt" field.
func AttemptLT(v int32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLT(FieldAttempt, v))
}

// AttemptLTE applies the LTE predicate on the "attempt" field.
func AttemptLTE(v int32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLTE(FieldAttempt, v))
}

// DurationMsEQ applies the EQ predicate on the "duration_ms" field.
func DurationMsEQ(v int64) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldDurationMs, v))
}

// DurationMsNEQ applies the NEQ predicate on the "duration_ms" field.
func DurationMsNEQ(v int64) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNEQ(FieldDurationMs, v))
}

// DurationMsIn applies the In predicate on the "duration_ms" field.
func DurationMsIn(vs ...int64) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldIn(FieldDurationMs, vs...))
}

// DurationMsNotIn applies the NotIn predicate on the "duration_ms" field.
func DurationMsNotIn(vs ...int64) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNotIn(FieldDurationMs, vs...))
}

// DurationMsGT applies the GT predicate on the "duration_ms" field.
func DurationMsGT(v int64) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGT(FieldDurationMs, v))
}

// DurationMsGTE applies the GTE predicate on the "duration_ms" field.
func DurationMsGTE(v int64) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGTE(FieldDurationMs, v))
}

// DurationMsLT applies the LT predicate on the "duration_ms" field.
func DurationMsLT(v int64) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLT(FieldDurationMs, v))
}

// DurationMsLTE applies the LTE predicate on the "duration_ms" field.
func DurationMsLTE(v int64) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLTE(FieldDurationMs, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNotNull(FieldFinishedAt))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uint32) predicate.TaskExecution {
	return predicate.TaskExecution(sql.FieldLTE(FieldTenantID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TaskExecution) predicate.TaskExecution {
	return predicate.TaskExecution(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TaskExecution) predicate.TaskExecution {
	return predicate.TaskExecution(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TaskExecution) predicate.TaskExecution {
	return predicate.TaskExecution(sql.NotPredicates(p))
}
